import type { BaseDef, DeviceTypeDef, ItemDef, RecipeDef } from './types'

const solidAllowance = { mode: 'solid' as const, whitelist: [] }
const liquidAllowance = { mode: 'liquid' as const, whitelist: [] }
const recipeItemsAllowance = { mode: 'recipe_items' as const, whitelist: [] }

export const ITEMS: ItemDef[] = [
  { id: 'item_bottled_food_1', displayName: '柑实罐头', type: 'solid' },
  { id: 'item_bottled_food_2', displayName: '优质柑实罐头', type: 'solid' },
  { id: 'item_bottled_food_3', displayName: '精选柑实罐头', type: 'solid' },
  { id: 'item_bottled_food_4', displayName: '锦草软饮', type: 'solid' },
  { id: 'item_bottled_rec_hp_1', displayName: '荞愈胶囊', type: 'solid' },
  { id: 'item_bottled_rec_hp_2', displayName: '优质荞愈胶囊', type: 'solid' },
  { id: 'item_bottled_rec_hp_3', displayName: '精选荞愈胶囊', type: 'solid' },
  { id: 'item_bottled_rec_hp_4', displayName: '芽针针剂', type: 'solid' },
  { id: 'item_carbon_enr', displayName: '稳定碳块', type: 'solid' },
  { id: 'item_carbon_enr_powder', displayName: '致密碳粉末', type: 'solid' },
  { id: 'item_carbon_mtl', displayName: '碳块', type: 'solid' },
  { id: 'item_carbon_powder', displayName: '碳粉末', type: 'solid' },
  { id: 'item_crystal_enr', displayName: '密制晶体', type: 'solid' },
  { id: 'item_crystal_enr_powder', displayName: '致密晶体粉末', type: 'solid' },
  { id: 'item_crystal_powder', displayName: '晶体外壳粉末', type: 'solid' },
  { id: 'item_crystal_shell', displayName: '晶体外壳', type: 'solid' },
  { id: 'item_equip_script_1', displayName: '紫晶装备原件', type: 'solid' },
  { id: 'item_equip_script_2', displayName: '蓝铁装备原件', type: 'solid' },
  { id: 'item_equip_script_3', displayName: '高晶装备原件', type: 'solid' },
  { id: 'item_equip_script_4', displayName: '息壤装备原件', type: 'solid' },
  { id: 'item_glass_bottle', displayName: '紫晶质瓶', type: 'solid' },
  { id: 'item_glass_cmpt', displayName: '紫晶零件', type: 'solid' },
  { id: 'item_glass_enr_bottle', displayName: '高晶质瓶', type: 'solid' },
  { id: 'item_glass_enr_cmpt', displayName: '高晶零件', type: 'solid' },
  { id: 'item_iron_bottle', displayName: '蓝铁瓶', type: 'solid' },
  { id: 'item_iron_cmpt', displayName: '铁制零件', type: 'solid' },
  { id: 'item_iron_enr', displayName: '钢块', type: 'solid' },
  { id: 'item_iron_enr_bottle', displayName: '钢质瓶', type: 'solid' },
  { id: 'item_iron_enr_cmpt', displayName: '钢制零件', type: 'solid' },
  { id: 'item_iron_enr_powder', displayName: '致密蓝铁粉末', type: 'solid' },
  { id: 'item_iron_nugget', displayName: '蓝铁块', type: 'solid' },
  { id: 'item_iron_ore', displayName: '蓝铁矿', type: 'solid', tags: ['矿石'] },
  { id: 'item_iron_powder', displayName: '蓝铁粉末', type: 'solid' },
  { id: 'item_liquid_plant_grass_1', displayName: '锦草溶液', type: 'solid' },
  { id: 'item_liquid_plant_grass_2', displayName: '芽针溶液', type: 'solid' },
  { id: 'item_liquid_water', displayName: '清水', type: 'solid' },
  { id: 'item_liquid_xiranite', displayName: '液化息壤', type: 'solid' },
  //{ id: 'item_muck_feces_1', displayName: '驮兽粪便', type: 'solid' },
  //{ id: 'item_muck_xiranite_1', displayName: '膨地啪', type: 'solid' },
  { id: 'item_originium_enr_powder', displayName: '致密源石粉末', type: 'solid' },
  { id: 'item_originium_ore', displayName: '源矿', type: 'solid', tags: ['矿石'] },
  { id: 'item_originium_powder', displayName: '源石粉末', type: 'solid' },
  { id: 'item_plant_bbflower_1', displayName: '酮化灌木', type: 'solid' },
  { id: 'item_plant_bbflower_powder_1', displayName: '酮化灌木粉末', type: 'solid' },
  { id: 'item_plant_bbflower_seed_1', displayName: '酮化树种', type: 'solid' },
  { id: 'item_plant_grass_1', displayName: '锦草', type: 'solid' },
  { id: 'item_plant_grass_2', displayName: '芽针', type: 'solid' },
  { id: 'item_plant_grass_powder_1', displayName: '锦草粉末', type: 'solid' },
  { id: 'item_plant_grass_powder_2', displayName: '芽针粉末', type: 'solid' },
  { id: 'item_plant_grass_seed_1', displayName: '锦草种子', type: 'solid' },
  { id: 'item_plant_grass_seed_2', displayName: '芽针种子', type: 'solid' },
  { id: 'item_plant_moss_1', displayName: '荞花', type: 'solid' },
  { id: 'item_plant_moss_2', displayName: '柑实', type: 'solid' },
  { id: 'item_plant_moss_3', displayName: '砂叶', type: 'solid' },
  { id: 'item_plant_moss_enr_powder_1', displayName: '细磨荞花粉末', type: 'solid' },
  { id: 'item_plant_moss_enr_powder_2', displayName: '细磨柑实粉末', type: 'solid' },
  { id: 'item_plant_moss_powder_1', displayName: '荞花粉末', type: 'solid' },
  { id: 'item_plant_moss_powder_2', displayName: '柑实粉末', type: 'solid' },
  { id: 'item_plant_moss_powder_3', displayName: '砂叶粉末', type: 'solid' },
  { id: 'item_plant_moss_seed_1', displayName: '荞花种子', type: 'solid' },
  { id: 'item_plant_moss_seed_2', displayName: '柑实种子', type: 'solid' },
  { id: 'item_plant_moss_seed_3', displayName: '砂叶种子', type: 'solid' },
  //{ id: 'item_plant_tundra_insect_powder_1', displayName: 'item_plant_tundra_insect_powder_1', type: 'solid' },
  //{ id: 'item_plant_tundra_insect_powder_2', displayName: 'item_plant_tundra_insect_powder_2', type: 'solid' },
  { id: 'item_proc_battery_1', displayName: '低容谷地电池', type: 'solid' },
  { id: 'item_proc_battery_2', displayName: '中容谷地电池', type: 'solid' },
  { id: 'item_proc_battery_3', displayName: '高容谷地电池', type: 'solid' },
  { id: 'item_proc_battery_4', displayName: '低容武陵电池', type: 'solid' },
  { id: 'item_proc_bomb_1', displayName: '工业爆炸物', type: 'solid' },
  { id: 'item_quartz_enr', displayName: '高晶纤维', type: 'solid' },
  { id: 'item_quartz_enr_powder', displayName: '高晶粉末', type: 'solid' },
  { id: 'item_quartz_glass', displayName: '紫晶纤维', type: 'solid' },
  { id: 'item_quartz_powder', displayName: '紫晶粉末', type: 'solid' },
  { id: 'item_quartz_sand', displayName: '紫晶矿', type: 'solid', tags: ['矿石'] },
  { id: 'item_xiranite_powder', displayName: '息壤', type: 'solid' },
]

export const RECIPES: RecipeDef[] = [
  {
    id: 'r_crusher_originium_powder_basic',
    machineType: 'item_port_grinder_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_originium_ore', amount: 1 }],
    outputs: [{ itemId: 'item_originium_powder', amount: 1 }],
  },
  {
    id: 'r_furnace_iron_nugget_from_iron_ore_basic',
    machineType: 'item_port_furnance_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_iron_ore', amount: 1 }],
    outputs: [{ itemId: 'item_iron_nugget', amount: 1 }],
  },
  {
    id: 'r_furnace_iron_nugget_from_iron_powder_basic',
    machineType: 'item_port_furnance_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_iron_powder', amount: 1 }],
    outputs: [{ itemId: 'item_iron_nugget', amount: 1 }],
  },
  {
    id: 'r_crusher_iron_powder_from_iron_nugget_basic',
    machineType: 'item_port_grinder_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_iron_nugget', amount: 1 }],
    outputs: [{ itemId: 'item_iron_powder', amount: 1 }],
  },
  {
    id: 'r_crusher_quartz_powder_from_quartz_glass_basic',
    machineType: 'item_port_grinder_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_quartz_glass', amount: 1 }],
    outputs: [{ itemId: 'item_quartz_powder', amount: 1 }],
  },
  {
    id: 'r_crusher_carbon_powder_from_carbon_mtl_basic',
    machineType: 'item_port_grinder_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_carbon_mtl', amount: 1 }],
    outputs: [{ itemId: 'item_carbon_powder', amount: 2 }],
  },
  {
    id: 'r_crusher_crystal_powder_from_crystal_shell_basic',
    machineType: 'item_port_grinder_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_crystal_shell', amount: 1 }],
    outputs: [{ itemId: 'item_crystal_powder', amount: 1 }],
  },
  {
    id: 'r_crusher_moss_powder_1_from_moss_1_basic',
    machineType: 'item_port_grinder_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_plant_moss_1', amount: 1 }],
    outputs: [{ itemId: 'item_plant_moss_powder_1', amount: 2 }],
  },
  {
    id: 'r_crusher_moss_powder_2_from_moss_2_basic',
    machineType: 'item_port_grinder_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_plant_moss_2', amount: 1 }],
    outputs: [{ itemId: 'item_plant_moss_powder_2', amount: 2 }],
  },
  {
    id: 'r_seedcol_moss_seed_from_moss_basic',
    machineType: 'item_port_seedcol_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_plant_moss_3', amount: 1 }],
    outputs: [{ itemId: 'item_plant_moss_seed_3', amount: 2 }],
  },
  {
    id: 'r_seedcol_moss_seed_1_from_moss_1_basic',
    machineType: 'item_port_seedcol_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_plant_moss_1', amount: 1 }],
    outputs: [{ itemId: 'item_plant_moss_seed_1', amount: 2 }],
  },
  {
    id: 'r_seedcol_moss_seed_2_from_moss_2_basic',
    machineType: 'item_port_seedcol_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_plant_moss_2', amount: 1 }],
    outputs: [{ itemId: 'item_plant_moss_seed_2', amount: 2 }],
  },
  {
    id: 'r_seedcol_bbflower_seed_from_bbflower_basic',
    machineType: 'item_port_seedcol_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_plant_bbflower_1', amount: 1 }],
    outputs: [{ itemId: 'item_plant_bbflower_seed_1', amount: 2 }],
  },
  {
    id: 'r_seedcol_grass_seed_1_from_grass_1_basic',
    machineType: 'item_port_seedcol_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_plant_grass_1', amount: 1 }],
    outputs: [{ itemId: 'item_plant_grass_seed_1', amount: 1 }],
  },
  {
    id: 'r_seedcol_grass_seed_2_from_grass_2_basic',
    machineType: 'item_port_seedcol_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_plant_grass_2', amount: 1 }],
    outputs: [{ itemId: 'item_plant_grass_seed_2', amount: 1 }],
  },
  {
    id: 'r_planter_moss_from_moss_seed_basic',
    machineType: 'item_port_planter_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_plant_moss_seed_3', amount: 1 }],
    outputs: [{ itemId: 'item_plant_moss_3', amount: 1 }],
  },
  {
    id: 'r_planter_moss_1_from_moss_seed_1_basic',
    machineType: 'item_port_planter_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_plant_moss_seed_1', amount: 1 }],
    outputs: [{ itemId: 'item_plant_moss_1', amount: 1 }],
  },
  {
    id: 'r_planter_moss_2_from_moss_seed_2_basic',
    machineType: 'item_port_planter_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_plant_moss_seed_2', amount: 1 }],
    outputs: [{ itemId: 'item_plant_moss_2', amount: 1 }],
  },
  {
    id: 'r_planter_bbflower_from_bbflower_seed_basic',
    machineType: 'item_port_planter_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_plant_bbflower_seed_1', amount: 1 }],
    outputs: [{ itemId: 'item_plant_bbflower_1', amount: 1 }],
  },
  {
    id: 'r_crusher_moss_powder_from_moss_basic',
    machineType: 'item_port_grinder_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_plant_moss_3', amount: 1 }],
    outputs: [{ itemId: 'item_plant_moss_powder_3', amount: 3 }],
  },
  {
    id: 'r_crusher_bbflower_powder_from_bbflower_basic',
    machineType: 'item_port_grinder_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_plant_bbflower_1', amount: 1 }],
    outputs: [{ itemId: 'item_plant_bbflower_powder_1', amount: 2 }],
  },
  {
    id: 'r_crusher_grass_powder_1_from_grass_1_basic',
    machineType: 'item_port_grinder_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_plant_grass_1', amount: 1 }],
    outputs: [{ itemId: 'item_plant_grass_powder_1', amount: 2 }],
  },
  {
    id: 'r_crusher_grass_powder_2_from_grass_2_basic',
    machineType: 'item_port_grinder_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_plant_grass_2', amount: 1 }],
    outputs: [{ itemId: 'item_plant_grass_powder_2', amount: 2 }],
  },
  {
    id: 'r_thickener_iron_enr_powder_from_iron_and_moss_powder_basic',
    machineType: 'item_port_thickener_1',
    cycleSeconds: 2,
    inputs: [
      { itemId: 'item_iron_powder', amount: 2 },
      { itemId: 'item_plant_moss_powder_3', amount: 1 },
    ],
    outputs: [{ itemId: 'item_iron_enr_powder', amount: 1 }],
  },
  {
    id: 'r_thickener_quartz_enr_powder_from_quartz_and_moss_powder_basic',
    machineType: 'item_port_thickener_1',
    cycleSeconds: 2,
    inputs: [
      { itemId: 'item_quartz_powder', amount: 2 },
      { itemId: 'item_plant_moss_powder_3', amount: 1 },
    ],
    outputs: [{ itemId: 'item_quartz_enr_powder', amount: 1 }],
  },
  {
    id: 'r_furnace_iron_enr_from_iron_enr_powder_basic',
    machineType: 'item_port_furnance_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_iron_enr_powder', amount: 1 }],
    outputs: [{ itemId: 'item_iron_enr', amount: 1 }],
  },
  {
    id: 'r_furnace_quartz_glass_from_quartz_sand_basic',
    machineType: 'item_port_furnance_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_quartz_sand', amount: 1 }],
    outputs: [{ itemId: 'item_quartz_glass', amount: 1 }],
  },
  {
    id: 'r_furnace_crystal_shell_from_originium_ore_basic',
    machineType: 'item_port_furnance_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_originium_ore', amount: 1 }],
    outputs: [{ itemId: 'item_crystal_shell', amount: 1 }],
  },
  {
    id: 'r_furnace_quartz_glass_from_quartz_powder_basic',
    machineType: 'item_port_furnance_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_quartz_powder', amount: 1 }],
    outputs: [{ itemId: 'item_quartz_glass', amount: 1 }],
  },
  {
    id: 'r_furnace_crystal_shell_from_crystal_powder_basic',
    machineType: 'item_port_furnance_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_crystal_powder', amount: 1 }],
    outputs: [{ itemId: 'item_crystal_shell', amount: 1 }],
  },
  {
    id: 'r_furnace_crystal_powder_from_originium_powder_basic',
    machineType: 'item_port_furnance_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_originium_powder', amount: 1 }],
    outputs: [{ itemId: 'item_crystal_powder', amount: 1 }],
  },
  {
    id: 'r_furnace_crystal_enr_powder_from_originium_enr_powder_basic',
    machineType: 'item_port_furnance_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_originium_enr_powder', amount: 1 }],
    outputs: [{ itemId: 'item_crystal_enr_powder', amount: 1 }],
  },
  {
    id: 'r_furnace_crystal_enr_from_crystal_enr_powder_basic',
    machineType: 'item_port_furnance_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_crystal_enr_powder', amount: 1 }],
    outputs: [{ itemId: 'item_crystal_enr', amount: 1 }],
  },
  {
    id: 'r_furnace_quartz_enr_from_quartz_enr_powder_basic',
    machineType: 'item_port_furnance_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_quartz_enr_powder', amount: 1 }],
    outputs: [{ itemId: 'item_quartz_enr', amount: 1 }],
  },
  {
    id: 'r_furnace_carbon_enr_from_carbon_enr_powder_basic',
    machineType: 'item_port_furnance_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_carbon_enr_powder', amount: 1 }],
    outputs: [{ itemId: 'item_carbon_enr', amount: 1 }],
  },
  {
    id: 'r_furnace_carbon_mtl_from_moss_1_basic',
    machineType: 'item_port_furnance_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_plant_moss_1', amount: 1 }],
    outputs: [{ itemId: 'item_carbon_mtl', amount: 1 }],
  },
  {
    id: 'r_furnace_carbon_mtl_from_moss_2_basic',
    machineType: 'item_port_furnance_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_plant_moss_2', amount: 1 }],
    outputs: [{ itemId: 'item_carbon_mtl', amount: 1 }],
  },
  {
    id: 'r_furnace_carbon_mtl_from_moss_3_basic',
    machineType: 'item_port_furnance_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_plant_moss_3', amount: 1 }],
    outputs: [{ itemId: 'item_carbon_mtl', amount: 1 }],
  },
  {
    id: 'r_furnace_carbon_mtl_from_grass_1_basic',
    machineType: 'item_port_furnance_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_plant_grass_1', amount: 1 }],
    outputs: [{ itemId: 'item_carbon_mtl', amount: 2 }],
  },
  {
    id: 'r_furnace_carbon_mtl_from_grass_2_basic',
    machineType: 'item_port_furnance_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_plant_grass_2', amount: 1 }],
    outputs: [{ itemId: 'item_carbon_mtl', amount: 2 }],
  },
  {
    id: 'r_furnace_carbon_powder_from_moss_powder_1_basic',
    machineType: 'item_port_furnance_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_plant_moss_powder_1', amount: 1 }],
    outputs: [{ itemId: 'item_carbon_powder', amount: 1 }],
  },
  {
    id: 'r_furnace_carbon_powder_from_moss_powder_2_basic',
    machineType: 'item_port_furnance_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_plant_moss_powder_2', amount: 1 }],
    outputs: [{ itemId: 'item_carbon_powder', amount: 1 }],
  },
  {
    id: 'r_furnace_carbon_powder_from_moss_powder_3_basic',
    machineType: 'item_port_furnance_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_plant_moss_powder_3', amount: 3 }],
    outputs: [{ itemId: 'item_carbon_powder', amount: 2 }],
  },
  {
    id: 'r_furnace_carbon_powder_from_grass_powder_1_basic',
    machineType: 'item_port_furnance_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_plant_grass_powder_1', amount: 1 }],
    outputs: [{ itemId: 'item_carbon_powder', amount: 2 }],
  },
  {
    id: 'r_furnace_carbon_powder_from_grass_powder_2_basic',
    machineType: 'item_port_furnance_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_plant_grass_powder_2', amount: 1 }],
    outputs: [{ itemId: 'item_carbon_powder', amount: 2 }],
  },
  {
    id: 'r_furnace_carbon_enr_powder_from_moss_enr_powder_1_basic',
    machineType: 'item_port_furnance_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_plant_moss_enr_powder_1', amount: 1 }],
    outputs: [{ itemId: 'item_carbon_enr_powder', amount: 1 }],
  },
  {
    id: 'r_furnace_carbon_enr_powder_from_moss_enr_powder_2_basic',
    machineType: 'item_port_furnance_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_plant_moss_enr_powder_2', amount: 1 }],
    outputs: [{ itemId: 'item_carbon_enr_powder', amount: 1 }],
  },
  {
    id: 'r_component_iron_enr_cmpt_from_iron_enr_basic',
    machineType: 'item_port_cmpt_mc_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_iron_enr', amount: 1 }],
    outputs: [{ itemId: 'item_iron_enr_cmpt', amount: 1 }],
  },
  {
    id: 'r_component_iron_cmpt_from_iron_nugget_basic',
    machineType: 'item_port_cmpt_mc_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_iron_nugget', amount: 1 }],
    outputs: [{ itemId: 'item_iron_cmpt', amount: 1 }],
  },
  {
    id: 'r_component_glass_cmpt_from_quartz_glass_basic',
    machineType: 'item_port_cmpt_mc_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_quartz_glass', amount: 1 }],
    outputs: [{ itemId: 'item_glass_cmpt', amount: 1 }],
  },
  {
    id: 'r_component_glass_enr_cmpt_from_quartz_enr_basic',
    machineType: 'item_port_cmpt_mc_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_quartz_enr', amount: 1 }],
    outputs: [{ itemId: 'item_glass_enr_cmpt', amount: 1 }],
  },
  {
    id: 'r_thickener_originium_enr_powder_from_originium_and_moss_powder_basic',
    machineType: 'item_port_thickener_1',
    cycleSeconds: 2,
    inputs: [
      { itemId: 'item_originium_powder', amount: 2 },
      { itemId: 'item_plant_moss_powder_3', amount: 1 },
    ],
    outputs: [{ itemId: 'item_originium_enr_powder', amount: 1 }],
  },
  {
    id: 'r_thickener_carbon_enr_powder_from_carbon_and_moss_powder_basic',
    machineType: 'item_port_thickener_1',
    cycleSeconds: 2,
    inputs: [
      { itemId: 'item_carbon_powder', amount: 2 },
      { itemId: 'item_plant_moss_powder_3', amount: 1 },
    ],
    outputs: [{ itemId: 'item_carbon_enr_powder', amount: 1 }],
  },
  {
    id: 'r_thickener_crystal_enr_powder_from_crystal_and_moss_powder_basic',
    machineType: 'item_port_thickener_1',
    cycleSeconds: 2,
    inputs: [
      { itemId: 'item_crystal_powder', amount: 2 },
      { itemId: 'item_plant_moss_powder_3', amount: 1 },
    ],
    outputs: [{ itemId: 'item_crystal_enr_powder', amount: 1 }],
  },
  {
    id: 'r_thickener_moss_enr_powder_1_from_moss_powder_1_and_moss_powder_basic',
    machineType: 'item_port_thickener_1',
    cycleSeconds: 2,
    inputs: [
      { itemId: 'item_plant_moss_powder_1', amount: 2 },
      { itemId: 'item_plant_moss_powder_3', amount: 1 },
    ],
    outputs: [{ itemId: 'item_plant_moss_enr_powder_1', amount: 1 }],
  },
  {
    id: 'r_thickener_moss_enr_powder_2_from_moss_powder_2_and_moss_powder_basic',
    machineType: 'item_port_thickener_1',
    cycleSeconds: 2,
    inputs: [
      { itemId: 'item_plant_moss_powder_2', amount: 2 },
      { itemId: 'item_plant_moss_powder_3', amount: 1 },
    ],
    outputs: [{ itemId: 'item_plant_moss_enr_powder_2', amount: 1 }],
  },
  {
    id: 'r_packaging_battery_from_iron_cmpt_and_originium_enr_powder_basic',
    machineType: 'item_port_tools_asm_mc_1',
    cycleSeconds: 10,
    inputs: [
      { itemId: 'item_iron_enr_cmpt', amount: 10 },
      { itemId: 'item_originium_enr_powder', amount: 15 },
    ],
    outputs: [{ itemId: 'item_proc_battery_3', amount: 1 }],
  },
  {
    id: 'r_packaging_bomb_from_glass_cmpt_and_bbflower_powder_basic',
    machineType: 'item_port_tools_asm_mc_1',
    cycleSeconds: 10,
    inputs: [
      { itemId: 'item_glass_cmpt', amount: 5 },
      { itemId: 'item_plant_bbflower_powder_1', amount: 1 },
    ],
    outputs: [{ itemId: 'item_proc_bomb_1', amount: 1 }],
  },
  {
    id: 'r_packaging_battery_1_from_glass_cmpt_and_originium_powder_basic',
    machineType: 'item_port_tools_asm_mc_1',
    cycleSeconds: 10,
    inputs: [
      { itemId: 'item_glass_cmpt', amount: 5 },
      { itemId: 'item_originium_powder', amount: 10 },
    ],
    outputs: [{ itemId: 'item_proc_battery_1', amount: 1 }],
  },
  {
    id: 'r_packaging_battery_2_from_iron_cmpt_and_originium_powder_basic',
    machineType: 'item_port_tools_asm_mc_1',
    cycleSeconds: 10,
    inputs: [
      { itemId: 'item_iron_cmpt', amount: 10 },
      { itemId: 'item_originium_powder', amount: 15 },
    ],
    outputs: [{ itemId: 'item_proc_battery_2', amount: 1 }],
  },
  {
    id: 'r_packaging_battery_4_from_xiranite_and_originium_enr_powder_basic',
    machineType: 'item_port_tools_asm_mc_1',
    cycleSeconds: 10,
    inputs: [
      { itemId: 'item_xiranite_powder', amount: 5 },
      { itemId: 'item_originium_enr_powder', amount: 15 },
    ],
    outputs: [{ itemId: 'item_proc_battery_4', amount: 1 }],
  },
  {
    id: 'r_winder_equip_script_1_from_crystal_shell_and_quartz_glass_basic',
    machineType: 'item_port_winder_1',
    cycleSeconds: 10,
    inputs: [
      { itemId: 'item_crystal_shell', amount: 5 },
      { itemId: 'item_quartz_glass', amount: 5 },
    ],
    outputs: [{ itemId: 'item_equip_script_1', amount: 1 }],
  },
  {
    id: 'r_winder_equip_script_2_from_crystal_shell_and_iron_nugget_basic',
    machineType: 'item_port_winder_1',
    cycleSeconds: 10,
    inputs: [
      { itemId: 'item_crystal_shell', amount: 10 },
      { itemId: 'item_iron_nugget', amount: 10 },
    ],
    outputs: [{ itemId: 'item_equip_script_2', amount: 1 }],
  },
  {
    id: 'r_winder_equip_script_3_from_crystal_enr_and_quartz_enr_basic',
    machineType: 'item_port_winder_1',
    cycleSeconds: 10,
    inputs: [
      { itemId: 'item_crystal_enr', amount: 10 },
      { itemId: 'item_quartz_enr', amount: 10 },
    ],
    outputs: [{ itemId: 'item_equip_script_3', amount: 1 }],
  },
  {
    id: 'r_winder_equip_script_4_from_crystal_enr_and_xiranite_powder_basic',
    machineType: 'item_port_winder_1',
    cycleSeconds: 10,
    inputs: [
      { itemId: 'item_crystal_enr', amount: 10 },
      { itemId: 'item_xiranite_powder', amount: 10 },
    ],
    outputs: [{ itemId: 'item_equip_script_4', amount: 1 }],
  },
  {
    id: 'r_filling_bottled_food_1_from_glass_bottle_and_moss_powder_2_basic',
    machineType: 'item_port_filling_pd_mc_1',
    cycleSeconds: 10,
    inputs: [
      { itemId: 'item_glass_bottle', amount: 5 },
      { itemId: 'item_plant_moss_powder_2', amount: 5 },
    ],
    outputs: [{ itemId: 'item_bottled_food_1', amount: 1 }],
  },
  {
    id: 'r_filling_bottled_food_2_from_iron_bottle_and_moss_powder_2_basic',
    machineType: 'item_port_filling_pd_mc_1',
    cycleSeconds: 10,
    inputs: [
      { itemId: 'item_iron_bottle', amount: 10 },
      { itemId: 'item_plant_moss_powder_2', amount: 10 },
    ],
    outputs: [{ itemId: 'item_bottled_food_2', amount: 1 }],
  },
  {
    id: 'r_filling_bottled_food_3_from_iron_enr_bottle_and_moss_enr_powder_2_basic',
    machineType: 'item_port_filling_pd_mc_1',
    cycleSeconds: 10,
    inputs: [
      { itemId: 'item_iron_enr_bottle', amount: 10 },
      { itemId: 'item_plant_moss_enr_powder_2', amount: 10 },
    ],
    outputs: [{ itemId: 'item_bottled_food_3', amount: 1 }],
  },
  {
    id: 'r_filling_bottled_rec_hp_1_from_glass_bottle_and_moss_powder_1_basic',
    machineType: 'item_port_filling_pd_mc_1',
    cycleSeconds: 10,
    inputs: [
      { itemId: 'item_glass_bottle', amount: 5 },
      { itemId: 'item_plant_moss_powder_1', amount: 5 },
    ],
    outputs: [{ itemId: 'item_bottled_rec_hp_1', amount: 1 }],
  },
  {
    id: 'r_filling_bottled_rec_hp_2_from_iron_bottle_and_moss_powder_1_basic',
    machineType: 'item_port_filling_pd_mc_1',
    cycleSeconds: 10,
    inputs: [
      { itemId: 'item_iron_bottle', amount: 10 },
      { itemId: 'item_plant_moss_powder_1', amount: 10 },
    ],
    outputs: [{ itemId: 'item_bottled_rec_hp_2', amount: 1 }],
  },
  {
    id: 'r_filling_bottled_rec_hp_3_from_iron_enr_bottle_and_moss_enr_powder_1_basic',
    machineType: 'item_port_filling_pd_mc_1',
    cycleSeconds: 10,
    inputs: [
      { itemId: 'item_iron_enr_bottle', amount: 10 },
      { itemId: 'item_plant_moss_enr_powder_1', amount: 10 },
    ],
    outputs: [{ itemId: 'item_bottled_rec_hp_3', amount: 1 }],
  },
  {
    id: 'r_shaper_iron_bottle_from_iron_nugget_basic',
    machineType: 'item_port_shaper_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_iron_nugget', amount: 2 }],
    outputs: [{ itemId: 'item_iron_bottle', amount: 1 }],
  },
  {
    id: 'r_shaper_glass_bottle_from_quartz_glass_basic',
    machineType: 'item_port_shaper_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_quartz_glass', amount: 2 }],
    outputs: [{ itemId: 'item_glass_bottle', amount: 1 }],
  },
  {
    id: 'r_shaper_iron_enr_bottle_from_iron_enr_basic',
    machineType: 'item_port_shaper_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_iron_enr', amount: 2 }],
    outputs: [{ itemId: 'item_iron_enr_bottle', amount: 1 }],
  },
  {
    id: 'r_shaper_glass_enr_bottle_from_quartz_enr_basic',
    machineType: 'item_port_shaper_1',
    cycleSeconds: 2,
    inputs: [{ itemId: 'item_quartz_enr', amount: 2 }],
    outputs: [{ itemId: 'item_glass_enr_bottle', amount: 1 }],
  },
]

export const DEVICE_TYPES: DeviceTypeDef[] = [
  {
    id: 'item_port_unloader_1',
    runtimeKind: 'storage',
    requiresPower: false,
    size: { width: 3, height: 1 },
    shortName: 'Pickup',
    placementConstraints: [
      {
        kind: 'edge_contact',
        edgeMode: 'opposite_of_port',
        portId: 'p_out_mid',
        minAdjacentCells: 1,
        targetTagsAny: ['bus'],
        violationMessageKey: 'toast.rule.pickupRequiresBus',
      },
    ],
    ports0: [
      {
        id: 'p_out_mid',
        localCellX: 1,
        localCellY: 0,
        edge: 'N',
        direction: 'Output',
        allowedItems: { mode: 'any', whitelist: [] },
        allowedTypes: solidAllowance,
      },
    ],
  },
  {
    id: 'item_port_grinder_1',
    runtimeKind: 'processor',
    requiresPower: true,
    size: { width: 3, height: 3 },
    shortName: 'Crusher',
    ports0: [
      ...[0, 1, 2].map((x) => ({
        id: `in_s_${x}`,
        localCellX: x,
        localCellY: 2,
        edge: 'S' as const,
        direction: 'Input' as const,
        allowedItems: { mode: 'recipe_inputs' as const, whitelist: [] },
        allowedTypes: solidAllowance,
      })),
      ...[0, 1, 2].map((x) => ({
        id: `out_n_${x}`,
        localCellX: x,
        localCellY: 0,
        edge: 'N' as const,
        direction: 'Output' as const,
        allowedItems: { mode: 'recipe_outputs' as const, whitelist: [] },
        allowedTypes: solidAllowance,
      })),
    ],
  },
  {
    id: 'item_port_furnance_1',
    runtimeKind: 'processor',
    requiresPower: true,
    size: { width: 3, height: 3 },
    shortName: 'Furnace',
    ports0: [
      ...[0, 1, 2].map((x) => ({
        id: `in_s_${x}`,
        localCellX: x,
        localCellY: 2,
        edge: 'S' as const,
        direction: 'Input' as const,
        allowedItems: { mode: 'recipe_inputs' as const, whitelist: [] },
        allowedTypes: solidAllowance,
      })),
      ...[0, 1, 2].map((x) => ({
        id: `out_n_${x}`,
        localCellX: x,
        localCellY: 0,
        edge: 'N' as const,
        direction: 'Output' as const,
        allowedItems: { mode: 'recipe_outputs' as const, whitelist: [] },
        allowedTypes: solidAllowance,
      })),
    ],
  },
  {
    id: 'item_port_cmpt_mc_1',
    runtimeKind: 'processor',
    requiresPower: true,
    size: { width: 3, height: 3 },
    shortName: 'Component',
    ports0: [
      ...[0, 1, 2].map((x) => ({
        id: `in_s_${x}`,
        localCellX: x,
        localCellY: 2,
        edge: 'S' as const,
        direction: 'Input' as const,
        allowedItems: { mode: 'recipe_inputs' as const, whitelist: [] },
        allowedTypes: solidAllowance,
      })),
      ...[0, 1, 2].map((x) => ({
        id: `out_n_${x}`,
        localCellX: x,
        localCellY: 0,
        edge: 'N' as const,
        direction: 'Output' as const,
        allowedItems: { mode: 'recipe_outputs' as const, whitelist: [] },
        allowedTypes: solidAllowance,
      })),
    ],
  },
  {
    id: 'item_port_shaper_1',
    runtimeKind: 'processor',
    requiresPower: true,
    size: { width: 3, height: 3 },
    shortName: 'Shaper',
    ports0: [
      ...[0, 1, 2].map((x) => ({
        id: `in_s_${x}`,
        localCellX: x,
        localCellY: 2,
        edge: 'S' as const,
        direction: 'Input' as const,
        allowedItems: { mode: 'recipe_inputs' as const, whitelist: [] },
        allowedTypes: solidAllowance,
      })),
      ...[0, 1, 2].map((x) => ({
        id: `out_n_${x}`,
        localCellX: x,
        localCellY: 0,
        edge: 'N' as const,
        direction: 'Output' as const,
        allowedItems: { mode: 'recipe_outputs' as const, whitelist: [] },
        allowedTypes: solidAllowance,
      })),
    ],
  },
  {
    id: 'item_port_seedcol_1',
    runtimeKind: 'processor',
    requiresPower: true,
    size: { width: 5, height: 5 },
    shortName: 'SeedCol',
    ports0: [
      ...[0, 1, 2, 3, 4].map((x) => ({
        id: `in_s_${x}`,
        localCellX: x,
        localCellY: 4,
        edge: 'S' as const,
        direction: 'Input' as const,
        allowedItems: { mode: 'recipe_inputs' as const, whitelist: [] },
        allowedTypes: solidAllowance,
      })),
      ...[0, 1, 2, 3, 4].map((x) => ({
        id: `out_n_${x}`,
        localCellX: x,
        localCellY: 0,
        edge: 'N' as const,
        direction: 'Output' as const,
        allowedItems: { mode: 'recipe_outputs' as const, whitelist: [] },
        allowedTypes: solidAllowance,
      })),
    ],
  },
  {
    id: 'item_port_planter_1',
    runtimeKind: 'processor',
    requiresPower: true,
    size: { width: 5, height: 5 },
    shortName: 'Planter',
    ports0: [
      ...[0, 1, 2, 3, 4].map((x) => ({
        id: `in_s_${x}`,
        localCellX: x,
        localCellY: 4,
        edge: 'S' as const,
        direction: 'Input' as const,
        allowedItems: { mode: 'recipe_inputs' as const, whitelist: [] },
        allowedTypes: solidAllowance,
      })),
      ...[0, 1, 2, 3, 4].map((x) => ({
        id: `out_n_${x}`,
        localCellX: x,
        localCellY: 0,
        edge: 'N' as const,
        direction: 'Output' as const,
        allowedItems: { mode: 'recipe_outputs' as const, whitelist: [] },
        allowedTypes: solidAllowance,
      })),
    ],
  },
  {
    id: 'item_port_winder_1',
    runtimeKind: 'processor',
    requiresPower: true,
    size: { width: 6, height: 4 },
    shortName: 'Winder',
    inputBufferSlots: 2,
    inputBufferSlotCapacities: [50, 50],
    ports0: [
      ...[0, 1, 2, 3, 4, 5].map((x) => ({
        id: `in_s_${x}`,
        localCellX: x,
        localCellY: 3,
        edge: 'S' as const,
        direction: 'Input' as const,
        allowedItems: { mode: 'recipe_inputs' as const, whitelist: [] },
        allowedTypes: solidAllowance,
      })),
      ...[0, 1, 2, 3, 4, 5].map((x) => ({
        id: `out_n_${x}`,
        localCellX: x,
        localCellY: 0,
        edge: 'N' as const,
        direction: 'Output' as const,
        allowedItems: { mode: 'recipe_outputs' as const, whitelist: [] },
        allowedTypes: solidAllowance,
      })),
    ],
  },
  {
    id: 'item_port_filling_pd_mc_1',
    runtimeKind: 'processor',
    requiresPower: true,
    size: { width: 6, height: 4 },
    shortName: 'Filling',
    inputBufferSlots: 2,
    inputBufferSlotCapacities: [50, 50],
    ports0: [
      ...[0, 1, 2, 3, 4, 5].map((x) => ({
        id: `in_s_${x}`,
        localCellX: x,
        localCellY: 3,
        edge: 'S' as const,
        direction: 'Input' as const,
        allowedItems: { mode: 'recipe_inputs' as const, whitelist: [] },
        allowedTypes: solidAllowance,
      })),
      ...[0, 1, 2, 3, 4, 5].map((x) => ({
        id: `out_n_${x}`,
        localCellX: x,
        localCellY: 0,
        edge: 'N' as const,
        direction: 'Output' as const,
        allowedItems: { mode: 'recipe_outputs' as const, whitelist: [] },
        allowedTypes: solidAllowance,
      })),
    ],
  },
  {
    id: 'item_port_tools_asm_mc_1',
    runtimeKind: 'processor',
    requiresPower: true,
    size: { width: 6, height: 4 },
    shortName: 'Pack',
    inputBufferSlots: 2,
    inputBufferSlotCapacities: [50, 50],
    ports0: [
      ...[0, 1, 2, 3, 4, 5].map((x) => ({
        id: `in_s_${x}`,
        localCellX: x,
        localCellY: 3,
        edge: 'S' as const,
        direction: 'Input' as const,
        allowedItems: { mode: 'recipe_inputs' as const, whitelist: [] },
        allowedTypes: solidAllowance,
      })),
      ...[0, 1, 2, 3, 4, 5].map((x) => ({
        id: `out_n_${x}`,
        localCellX: x,
        localCellY: 0,
        edge: 'N' as const,
        direction: 'Output' as const,
        allowedItems: { mode: 'recipe_outputs' as const, whitelist: [] },
        allowedTypes: solidAllowance,
      })),
    ],
  },
  {
    id: 'item_port_thickener_1',
    runtimeKind: 'processor',
    requiresPower: true,
    size: { width: 6, height: 4 },
    shortName: 'Thicken',
    inputBufferSlots: 2,
    inputBufferSlotCapacities: [50, 50],
    ports0: [
      ...[0, 1, 2, 3, 4, 5].map((x) => ({
        id: `in_s_${x}`,
        localCellX: x,
        localCellY: 3,
        edge: 'S' as const,
        direction: 'Input' as const,
        allowedItems: { mode: 'recipe_inputs' as const, whitelist: [] },
        allowedTypes: solidAllowance,
      })),
      ...[0, 1, 2, 3, 4, 5].map((x) => ({
        id: `out_n_${x}`,
        localCellX: x,
        localCellY: 0,
        edge: 'N' as const,
        direction: 'Output' as const,
        allowedItems: { mode: 'recipe_outputs' as const, whitelist: [] },
        allowedTypes: solidAllowance,
      })),
    ],
  },
  {
    id: 'item_port_power_sta_1',
    runtimeKind: 'processor',
    requiresPower: true,
    size: { width: 2, height: 2 },
    shortName: 'HeatPool',
    ports0: [
      ...[0, 1].map((x) => ({
        id: `in_s_${x}`,
        localCellX: x,
        localCellY: 1,
        edge: 'S' as const,
        direction: 'Input' as const,
        allowedItems: { mode: 'recipe_inputs' as const, whitelist: [] },
        allowedTypes: solidAllowance,
      })),
    ],
  },
  {
    id: 'item_port_mix_pool_1',
    runtimeKind: 'processor',
    requiresPower: true,
    size: { width: 5, height: 5 },
    shortName: 'MixPool',
    tags: ['武陵'],
    ports0: [
      ...[1, 3].map((x) => ({
        id: `out_n_${x}`,
        localCellX: x,
        localCellY: 0,
        edge: 'N' as const,
        direction: 'Output' as const,
        allowedItems: { mode: 'recipe_outputs' as const, whitelist: [] },
        allowedTypes: solidAllowance,
      })),
      ...[1, 3].map((x) => ({
        id: `in_s_${x}`,
        localCellX: x,
        localCellY: 4,
        edge: 'S' as const,
        direction: 'Input' as const,
        allowedItems: { mode: 'recipe_inputs' as const, whitelist: [] },
        allowedTypes: solidAllowance,
      })),
      ...[1, 3].map((y) => ({
        id: `out_w_${y}`,
        localCellX: 0,
        localCellY: y,
        edge: 'W' as const,
        direction: 'Output' as const,
        allowedItems: { mode: 'recipe_outputs' as const, whitelist: [] },
        allowedTypes: liquidAllowance,
      })),
      ...[1, 3].map((y) => ({
        id: `in_e_${y}`,
        localCellX: 4,
        localCellY: y,
        edge: 'E' as const,
        direction: 'Input' as const,
        allowedItems: { mode: 'recipe_inputs' as const, whitelist: [] },
        allowedTypes: liquidAllowance,
      })),
    ],
  },
  {
    id: 'item_port_xiranite_oven_1',
    runtimeKind: 'processor',
    requiresPower: true,
    size: { width: 5, height: 5 },
    shortName: 'XiraniteOven',
    tags: ['武陵'],
    ports0: [
      ...[0, 1, 2, 3, 4].map((x) => ({
        id: `out_n_${x}`,
        localCellX: x,
        localCellY: 0,
        edge: 'N' as const,
        direction: 'Output' as const,
        allowedItems: { mode: 'recipe_outputs' as const, whitelist: [] },
        allowedTypes: solidAllowance,
      })),
      ...[0, 1, 2, 3, 4].map((x) => ({
        id: `in_s_${x}`,
        localCellX: x,
        localCellY: 4,
        edge: 'S' as const,
        direction: 'Input' as const,
        allowedItems: { mode: 'recipe_inputs' as const, whitelist: [] },
        allowedTypes: solidAllowance,
      })),
      {
        id: 'in_e_2',
        localCellX: 4,
        localCellY: 2,
        edge: 'E',
        direction: 'Input',
        allowedItems: { mode: 'recipe_inputs', whitelist: [] },
        allowedTypes: liquidAllowance,
      },
    ],
  },
  {
    id: 'item_port_dismantler_1',
    runtimeKind: 'processor',
    requiresPower: true,
    size: { width: 6, height: 4 },
    shortName: 'Dismantler',
    tags: ['武陵'],
    ports0: [
      ...[0, 1, 2, 3, 4, 5].map((x) => ({
        id: `out_n_${x}`,
        localCellX: x,
        localCellY: 0,
        edge: 'N' as const,
        direction: 'Output' as const,
        allowedItems: { mode: 'recipe_outputs' as const, whitelist: [] },
        allowedTypes: solidAllowance,
      })),
      ...[0, 1, 2, 3, 4, 5].map((x) => ({
        id: `in_s_${x}`,
        localCellX: x,
        localCellY: 3,
        edge: 'S' as const,
        direction: 'Input' as const,
        allowedItems: { mode: 'recipe_inputs' as const, whitelist: [] },
        allowedTypes: solidAllowance,
      })),
      {
        id: 'out_w_2',
        localCellX: 0,
        localCellY: 2,
        edge: 'W',
        direction: 'Output',
        allowedItems: { mode: 'recipe_outputs', whitelist: [] },
        allowedTypes: liquidAllowance,
      },
    ],
  },
  {
    id: 'item_port_log_hongs_bus_source',
    runtimeKind: 'storage',
    requiresPower: false,
    size: { width: 4, height: 4 },
    shortName: 'BusSource',
    tags: ['武陵', 'bus'],
    ports0: [],
  },
  {
    id: 'item_port_log_hongs_bus',
    runtimeKind: 'storage',
    requiresPower: false,
    size: { width: 4, height: 8 },
    shortName: 'BusSegment',
    tags: ['武陵', 'bus'],
    ports0: [],
  },
  {
    id: 'item_port_water_pump_1',
    runtimeKind: 'storage',
    requiresPower: false,
    size: { width: 3, height: 3 },
    shortName: 'WaterPump',
    tags: ['武陵'],
    ports0: [
      {
        id: 'out_e_1',
        localCellX: 2,
        localCellY: 1,
        edge: 'E',
        direction: 'Output',
        allowedItems: { mode: 'whitelist', whitelist: ['item_liquid_water'] },
        allowedTypes: liquidAllowance,
      },
    ],
  },
  {
    id: 'item_port_liquid_storager_1',
    runtimeKind: 'storage',
    requiresPower: false,
    size: { width: 3, height: 3 },
    shortName: 'LiquidStorage',
    tags: ['武陵'],
    ports0: [
      {
        id: 'in_w_1',
        localCellX: 0,
        localCellY: 1,
        edge: 'W',
        direction: 'Input',
        allowedItems: { mode: 'recipe_items', whitelist: [] },
        allowedTypes: liquidAllowance,
      },
      {
        id: 'out_e_1',
        localCellX: 2,
        localCellY: 1,
        edge: 'E',
        direction: 'Output',
        allowedItems: { mode: 'recipe_items', whitelist: [] },
        allowedTypes: liquidAllowance,
      },
    ],
  },
  {
    id: 'item_port_power_diffuser_1',
    runtimeKind: 'storage',
    requiresPower: false,
    size: { width: 2, height: 2 },
    shortName: 'Pole',
    ports0: [],
  },
  {
    id: 'item_port_storager_1',
    runtimeKind: 'storage',
    requiresPower: false,
    size: { width: 3, height: 3 },
    shortName: 'Storage',
    ports0: [
      ...[0, 1, 2].map((x) => ({
        id: `in_s_${x}`,
        localCellX: x,
        localCellY: 2,
        edge: 'S' as const,
        direction: 'Input' as const,
        allowedItems: recipeItemsAllowance,
        allowedTypes: solidAllowance,
      })),
      ...[0, 1, 2].map((x) => ({
        id: `out_n_${x}`,
        localCellX: x,
        localCellY: 0,
        edge: 'N' as const,
        direction: 'Output' as const,
        allowedItems: recipeItemsAllowance,
        allowedTypes: solidAllowance,
      })),
    ],
  },
  {
    id: 'belt_straight_1x1',
    runtimeKind: 'conveyor',
    requiresPower: false,
    size: { width: 1, height: 1 },
    shortName: 'Belt',
    ports0: [
      {
        id: 'in_w',
        localCellX: 0,
        localCellY: 0,
        edge: 'W',
        direction: 'Input',
        allowedItems: recipeItemsAllowance,
        allowedTypes: solidAllowance,
      },
      {
        id: 'out_e',
        localCellX: 0,
        localCellY: 0,
        edge: 'E',
        direction: 'Output',
        allowedItems: recipeItemsAllowance,
        allowedTypes: solidAllowance,
      },
    ],
  },
  {
    id: 'belt_turn_cw_1x1',
    runtimeKind: 'conveyor',
    requiresPower: false,
    size: { width: 1, height: 1 },
    shortName: 'Turn↱',
    ports0: [
      {
        id: 'in_n',
        localCellX: 0,
        localCellY: 0,
        edge: 'N',
        direction: 'Input',
        allowedItems: recipeItemsAllowance,
        allowedTypes: solidAllowance,
      },
      {
        id: 'out_e',
        localCellX: 0,
        localCellY: 0,
        edge: 'E',
        direction: 'Output',
        allowedItems: recipeItemsAllowance,
        allowedTypes: solidAllowance,
      },
    ],
  },
  {
    id: 'belt_turn_ccw_1x1',
    runtimeKind: 'conveyor',
    requiresPower: false,
    size: { width: 1, height: 1 },
    shortName: 'Turn↰',
    ports0: [
      {
        id: 'in_n',
        localCellX: 0,
        localCellY: 0,
        edge: 'N',
        direction: 'Input',
        allowedItems: recipeItemsAllowance,
        allowedTypes: solidAllowance,
      },
      {
        id: 'out_w',
        localCellX: 0,
        localCellY: 0,
        edge: 'W',
        direction: 'Output',
        allowedItems: recipeItemsAllowance,
        allowedTypes: solidAllowance,
      },
    ],
  },
  {
    id: 'pipe_straight_1x1',
    runtimeKind: 'conveyor',
    requiresPower: false,
    size: { width: 1, height: 1 },
    shortName: 'Pipe',
    tags: ['武陵'],
    ports0: [
      {
        id: 'in_w',
        localCellX: 0,
        localCellY: 0,
        edge: 'W',
        direction: 'Input',
        allowedItems: recipeItemsAllowance,
        allowedTypes: liquidAllowance,
      },
      {
        id: 'out_e',
        localCellX: 0,
        localCellY: 0,
        edge: 'E',
        direction: 'Output',
        allowedItems: recipeItemsAllowance,
        allowedTypes: liquidAllowance,
      },
    ],
  },
  {
    id: 'pipe_turn_cw_1x1',
    runtimeKind: 'conveyor',
    requiresPower: false,
    size: { width: 1, height: 1 },
    shortName: 'PipeTurn↱',
    tags: ['武陵'],
    ports0: [
      {
        id: 'in_n',
        localCellX: 0,
        localCellY: 0,
        edge: 'N',
        direction: 'Input',
        allowedItems: recipeItemsAllowance,
        allowedTypes: liquidAllowance,
      },
      {
        id: 'out_e',
        localCellX: 0,
        localCellY: 0,
        edge: 'E',
        direction: 'Output',
        allowedItems: recipeItemsAllowance,
        allowedTypes: liquidAllowance,
      },
    ],
  },
  {
    id: 'pipe_turn_ccw_1x1',
    runtimeKind: 'conveyor',
    requiresPower: false,
    size: { width: 1, height: 1 },
    shortName: 'PipeTurn↰',
    tags: ['武陵'],
    ports0: [
      {
        id: 'in_n',
        localCellX: 0,
        localCellY: 0,
        edge: 'N',
        direction: 'Input',
        allowedItems: recipeItemsAllowance,
        allowedTypes: liquidAllowance,
      },
      {
        id: 'out_w',
        localCellX: 0,
        localCellY: 0,
        edge: 'W',
        direction: 'Output',
        allowedItems: recipeItemsAllowance,
        allowedTypes: liquidAllowance,
      },
    ],
  },
  {
    id: 'item_log_splitter',
    runtimeKind: 'junction',
    requiresPower: false,
    size: { width: 1, height: 1 },
    shortName: 'Split',
    ports0: [
      {
        id: 'in_e',
        localCellX: 0,
        localCellY: 0,
        edge: 'E',
        direction: 'Input',
        allowedItems: recipeItemsAllowance,
        allowedTypes: solidAllowance,
      },
      ...(['N', 'W', 'S'] as const).map((edge) => ({
        id: `out_${edge.toLowerCase()}`,
        localCellX: 0,
        localCellY: 0,
        edge,
        direction: 'Output' as const,
        allowedItems: recipeItemsAllowance,
        allowedTypes: solidAllowance,
      })),
    ],
  },
  {
    id: 'item_log_converger',
    runtimeKind: 'junction',
    requiresPower: false,
    size: { width: 1, height: 1 },
    shortName: 'Merge',
    ports0: [
      ...(['N', 'E', 'S'] as const).map((edge) => ({
        id: `in_${edge.toLowerCase()}`,
        localCellX: 0,
        localCellY: 0,
        edge,
        direction: 'Input' as const,
        allowedItems: recipeItemsAllowance,
        allowedTypes: solidAllowance,
      })),
      {
        id: 'out_w',
        localCellX: 0,
        localCellY: 0,
        edge: 'W',
        direction: 'Output',
        allowedItems: recipeItemsAllowance,
        allowedTypes: solidAllowance,
      },
    ],
  },
  {
    id: 'item_log_connector',
    runtimeKind: 'junction',
    requiresPower: false,
    size: { width: 1, height: 1 },
    shortName: 'Bridge',
    ports0: (['N', 'S', 'W', 'E'] as const).flatMap((edge) => [
      {
        id: `in_${edge.toLowerCase()}`,
        localCellX: 0,
        localCellY: 0,
        edge,
        direction: 'Input' as const,
        allowedItems: recipeItemsAllowance,
        allowedTypes: solidAllowance,
      },
      {
        id: `out_${edge.toLowerCase()}`,
        localCellX: 0,
        localCellY: 0,
        edge,
        direction: 'Output' as const,
        allowedItems: recipeItemsAllowance,
        allowedTypes: solidAllowance,
      },
    ]),
  },
  {
    id: 'item_pipe_splitter',
    runtimeKind: 'junction',
    requiresPower: false,
    size: { width: 1, height: 1 },
    shortName: 'PipeSplit',
    tags: ['武陵'],
    ports0: [
      {
        id: 'in_e',
        localCellX: 0,
        localCellY: 0,
        edge: 'E',
        direction: 'Input',
        allowedItems: recipeItemsAllowance,
        allowedTypes: liquidAllowance,
      },
      ...(['N', 'W', 'S'] as const).map((edge) => ({
        id: `out_${edge.toLowerCase()}`,
        localCellX: 0,
        localCellY: 0,
        edge,
        direction: 'Output' as const,
        allowedItems: recipeItemsAllowance,
        allowedTypes: liquidAllowance,
      })),
    ],
  },
  {
    id: 'item_pipe_converger',
    runtimeKind: 'junction',
    requiresPower: false,
    size: { width: 1, height: 1 },
    shortName: 'PipeMerge',
    tags: ['武陵'],
    ports0: [
      ...(['N', 'E', 'S'] as const).map((edge) => ({
        id: `in_${edge.toLowerCase()}`,
        localCellX: 0,
        localCellY: 0,
        edge,
        direction: 'Input' as const,
        allowedItems: recipeItemsAllowance,
        allowedTypes: liquidAllowance,
      })),
      {
        id: 'out_w',
        localCellX: 0,
        localCellY: 0,
        edge: 'W',
        direction: 'Output',
        allowedItems: recipeItemsAllowance,
        allowedTypes: liquidAllowance,
      },
    ],
  },
  {
    id: 'item_pipe_connector',
    runtimeKind: 'junction',
    requiresPower: false,
    size: { width: 1, height: 1 },
    shortName: 'PipeBridge',
    tags: ['武陵'],
    ports0: (['N', 'S', 'W', 'E'] as const).flatMap((edge) => [
      {
        id: `in_${edge.toLowerCase()}`,
        localCellX: 0,
        localCellY: 0,
        edge,
        direction: 'Input' as const,
        allowedItems: recipeItemsAllowance,
        allowedTypes: liquidAllowance,
      },
      {
        id: `out_${edge.toLowerCase()}`,
        localCellX: 0,
        localCellY: 0,
        edge,
        direction: 'Output' as const,
        allowedItems: recipeItemsAllowance,
        allowedTypes: liquidAllowance,
      },
    ]),
  },
]

export const DEVICE_TYPE_BY_ID: Record<string, DeviceTypeDef> = Object.fromEntries(
  DEVICE_TYPES.map((deviceType) => [deviceType.id, deviceType]),
)

export const ITEM_BY_ID: Record<string, ItemDef> = Object.fromEntries(ITEMS.map((item) => [item.id, item]))

export const PLACEABLE_TYPES = DEVICE_TYPES.filter(
  (deviceType) => !deviceType.id.startsWith('belt_') && !deviceType.id.startsWith('pipe_'),
)

export const BELT_TYPES = new Set(['belt_straight_1x1', 'belt_turn_cw_1x1', 'belt_turn_ccw_1x1'])
export const PIPE_TYPES = new Set(['pipe_straight_1x1', 'pipe_turn_cw_1x1', 'pipe_turn_ccw_1x1'])
export const JUNCTION_TYPES = new Set(['item_log_splitter', 'item_log_converger', 'item_log_connector'])
export const PIPE_JUNCTION_TYPES = new Set(['item_pipe_splitter', 'item_pipe_converger', 'item_pipe_connector'])

export const BASES: BaseDef[] = [
  {
    id: 'wuling_protocol_core',
    name: '协议核心区',
    placeableSize: 80,
    outerRing: { top: 3, right: 3, bottom: 3, left: 3 },
    tags: ['武陵'],
    foundationBuildings: [],
  },
  {
    id: 'valley4_protocol_core',
    name: '协议核心区',
    placeableSize: 70,
    outerRing: { top: 4, right: 2, bottom: 2, left: 4 },
    tags: ['四号谷地'],
    foundationBuildings: [
      {
        instanceId: 'base_valley4_bus_source_1',
        typeId: 'item_port_log_hongs_bus_source',
        origin: { x: -4, y: -4 },
        rotation: 0,
      },
      ...Array.from({ length: 9 }, (_, index) => ({
        instanceId: `base_valley4_bus_right_${index + 1}`,
        typeId: 'item_port_log_hongs_bus' as const,
        origin: { x: index * 8, y: -4 },
        rotation: 90 as const,
      })),
      ...Array.from({ length: 9 }, (_, index) => ({
        instanceId: `base_valley4_bus_down_${index + 1}`,
        typeId: 'item_port_log_hongs_bus' as const,
        origin: { x: -4, y: index * 8 },
        rotation: 0 as const,
      })),
    ],
  },
  {
    id: 'valley4_refugee_shelter',
    name: '难民暂居处',
    placeableSize: 40,
    outerRing: { top: 4, right: 0, bottom: 0, left: 0 },
    tags: ['四号谷地'],
    foundationBuildings: Array.from({ length: 5 }, (_, index) => ({
      instanceId: `base_valley4_refugee_top_${index + 1}`,
      typeId: 'item_port_log_hongs_bus' as const,
      origin: { x: index * 8, y: -4 },
      rotation: 90 as const,
    })),
  },
  {
    id: 'valley4_infra_outpost',
    name: '基建前站',
    placeableSize: 40,
    outerRing: { top: 4, right: 0, bottom: 0, left: 0 },
    tags: ['四号谷地'],
    foundationBuildings: Array.from({ length: 5 }, (_, index) => ({
      instanceId: `base_valley4_infra_top_${index + 1}`,
      typeId: 'item_port_log_hongs_bus' as const,
      origin: { x: index * 8, y: -4 },
      rotation: 90 as const,
    })),
  },
  {
    id: 'valley4_rebuilt_command',
    name: '重建指挥部',
    placeableSize: 40,
    outerRing: { top: 4, right: 0, bottom: 0, left: 0 },
    tags: ['四号谷地'],
    foundationBuildings: Array.from({ length: 5 }, (_, index) => ({
      instanceId: `base_valley4_rebuild_top_${index + 1}`,
      typeId: 'item_port_log_hongs_bus' as const,
      origin: { x: index * 8, y: -4 },
      rotation: 90 as const,
    })),
  },
]

export const BASE_BY_ID: Record<string, BaseDef> = Object.fromEntries(BASES.map((base) => [base.id, base]))

function validateRegistryConsistency() {
  const errors: string[] = []
  const recipeIdSet = new Set<string>()
  const itemIdSet = new Set<string>()

  for (const item of ITEMS) {
    if (itemIdSet.has(item.id)) {
      errors.push(`重复物品ID: ${item.id}`)
      continue
    }
    itemIdSet.add(item.id)
  }

  for (const recipe of RECIPES) {
    if (recipeIdSet.has(recipe.id)) {
      errors.push(`重复配方ID: ${recipe.id}`)
      continue
    }
    recipeIdSet.add(recipe.id)

    if (!DEVICE_TYPE_BY_ID[recipe.machineType]) {
      errors.push(`配方 ${recipe.id} 引用了未定义设备: ${recipe.machineType}`)
    }

    for (const input of recipe.inputs) {
      if (!itemIdSet.has(input.itemId)) {
        errors.push(`配方 ${recipe.id} 输入物品未定义: ${input.itemId}`)
      }
    }

    for (const output of recipe.outputs) {
      if (!itemIdSet.has(output.itemId)) {
        errors.push(`配方 ${recipe.id} 输出物品未定义: ${output.itemId}`)
      }
    }
  }

  if (errors.length > 0) {
    throw new Error(`领域模型/Registry 校验失败:\n${errors.map((message) => `- ${message}`).join('\n')}`)
  }
}

validateRegistryConsistency()
