import type { EntityDefinition } from "@/domain/types/registry/entity-definition";

export const ENTITY_DEFINITIONS: EntityDefinition[] = [
  {
    id: "item_port_storager_1",
    nameKey: "registry.entity.item_port_storager_1.name",
    footprint: { width: 3, height: 3 },
    spiriteId: "",
    tags: [],
  },
  {
    id: "item_port_log_hongs_bus",
    nameKey: "registry.entity.item_port_log_hongs_bus.name",
    footprint: { width: 4, height: 8 },
    spiriteId: "",
    tags: [],
  },
  {
    id: "item_port_log_hongs_bus_source",
    nameKey: "registry.entity.item_port_log_hongs_bus_source.name",
    footprint: { width: 4, height: 4 },
    spiriteId: "",
    tags: [],
  },
  {
    id: "item_port_unloader_1",
    nameKey: "registry.entity.item_port_unloader_1.name",
    footprint: { width: 3, height: 1 },
    spiriteId: "",
    tags: [],
  },
  {
    id: "item_port_mix_pool_1",
    nameKey: "registry.entity.item_port_mix_pool_1.name",
    footprint: { width: 5, height: 5 },
    spiriteId: "",
    tags: [],
  },
  {
    id: "item_port_grinder_1",
    nameKey: "registry.entity.item_port_grinder_1.name",
    footprint: { width: 3, height: 3 },
    spiriteId: "",
    tags: [],
  },
  {
    id: "item_port_liquid_filling_pd_mc_1",
    nameKey: "registry.entity.item_port_liquid_filling_pd_mc_1.name",
    footprint: { width: 6, height: 4 },
    spiriteId: "",
    tags: [],
  },
  {
    id: "belt_straight_1x1",
    nameKey: "registry.entity.belt_straight_1x1.name",
    footprint: { width: 1, height: 1 },
    spiriteId: "",
    tags: [],
  },
  {
    id: "item_log_splitter",
    nameKey: "registry.entity.item_log_splitter.name",
    footprint: { width: 1, height: 1 },
    spiriteId: "",
    tags: [],
  },
  {
    id: "item_log_converger",
    nameKey: "registry.entity.item_log_converger.name",
    footprint: { width: 1, height: 1 },
    spiriteId: "",
    tags: [],
  },
  {
    id: "item_log_connector",
    nameKey: "registry.entity.item_log_connector.name",
    footprint: { width: 1, height: 1 },
    spiriteId: "",
    tags: [],
  },
  {
    id: "pipe_straight_1x1",
    nameKey: "registry.entity.pipe_straight_1x1.name",
    footprint: { width: 1, height: 1 },
    spiriteId: "",
    tags: [],
  },
  {
    id: "item_pipe_splitter",
    nameKey: "registry.entity.item_pipe_splitter.name",
    footprint: { width: 1, height: 1 },
    spiriteId: "",
    tags: [],
  },
  {
    id: "item_pipe_converger",
    nameKey: "registry.entity.item_pipe_converger.name",
    footprint: { width: 1, height: 1 },
    spiriteId: "",
    tags: [],
  },
  {
    id: "item_pipe_connector",
    nameKey: "registry.entity.item_pipe_connector.name",
    footprint: { width: 1, height: 1 },
    spiriteId: "",
    tags: [],
  },
  {
    id: "item_port_udpipe_loader_1",
    nameKey: "registry.entity.item_port_udpipe_loader_1.name",
    footprint: { width: 3, height: 3 },
    spiriteId: "",
    tags: [],
  },
  {
    id: "item_port_udpipe_unloader_1",
    nameKey: "registry.entity.item_port_udpipe_unloader_1.name",
    footprint: { width: 3, height: 3 },
    spiriteId: "",
    tags: [],
  },
];
