import type { ItemDefinition } from "@/domain/registry/types/item-definition";
import { ACTIVITY_LIMITED_FORMULA_1_TAG } from "@/shared/registry/activity-availability";

export const ITEM_DEFINITIONS: ItemDefinition[] = [
  {
    id: "item_bottled_food_1",
    nameKey: "registry.item.item_bottled_food_1.name",
    iconId: "item_bottled_food_1",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_bottled_food_2",
    nameKey: "registry.item.item_bottled_food_2.name",
    iconId: "item_bottled_food_2",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_bottled_food_3",
    nameKey: "registry.item.item_bottled_food_3.name",
    iconId: "item_bottled_food_3",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_bottled_food_4",
    nameKey: "registry.item.item_bottled_food_4.name",
    iconId: "item_bottled_food_4",
    tags: ["调度券地区:武陵", "调度券价值:16"],
    displayOrder: 10000,
  },
  {
    id: "item_bottled_food_5",
    nameKey: "registry.item.item_bottled_food_5.name",
    iconId: "item_bottled_food_5",
    tags: ["调度券地区:武陵", "调度券价值:22"],
    displayOrder: 10000,
  },
  {
    id: "item_bottled_rec_hp_1",
    nameKey: "registry.item.item_bottled_rec_hp_1.name",
    iconId: "item_bottled_rec_hp_1",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_bottled_rec_hp_2",
    nameKey: "registry.item.item_bottled_rec_hp_2.name",
    iconId: "item_bottled_rec_hp_2",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_bottled_rec_hp_3",
    nameKey: "registry.item.item_bottled_rec_hp_3.name",
    iconId: "item_bottled_rec_hp_3",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_bottled_rec_hp_4",
    nameKey: "registry.item.item_bottled_rec_hp_4.name",
    iconId: "item_bottled_rec_hp_4",
    tags: ["调度券地区:武陵", "调度券价值:16"],
    displayOrder: 10000,
  },
  {
    id: "item_bottled_rec_hp_5",
    nameKey: "registry.item.item_bottled_rec_hp_5.name",
    iconId: "item_bottled_rec_hp_5",
    tags: ["调度券地区:武陵", "调度券价值:22"],
    displayOrder: 10000,
  },
  {
    id: "item_carbon_enr",
    nameKey: "registry.item.item_carbon_enr.name",
    iconId: "item_carbon_enr",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_carbon_enr_powder",
    nameKey: "registry.item.item_carbon_enr_powder.name",
    iconId: "item_carbon_enr_powder",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_carbon_mtl",
    nameKey: "registry.item.item_carbon_mtl.name",
    iconId: "item_carbon_mtl",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_carbon_powder",
    nameKey: "registry.item.item_carbon_powder.name",
    iconId: "item_carbon_powder",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_crystal_enr",
    nameKey: "registry.item.item_crystal_enr.name",
    iconId: "item_crystal_enr",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_crystal_enr_powder",
    nameKey: "registry.item.item_crystal_enr_powder.name",
    iconId: "item_crystal_enr_powder",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_crystal_powder",
    nameKey: "registry.item.item_crystal_powder.name",
    iconId: "item_crystal_powder",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_crystal_shell",
    nameKey: "registry.item.item_crystal_shell.name",
    iconId: "item_crystal_shell",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_copper_ore",
    nameKey: "registry.item.item_copper_ore.name",
    iconId: "item_copper_ore",
    tags: ["矿石", "自然资源"],
    displayOrder: 10000,
  },
  {
    id: "item_copper_bottle",
    nameKey: "registry.item.item_copper_bottle.name",
    iconId: "item_copper_bottle",
    tags: ["瓶子"],
    displayOrder: 10000,
  },
  {
    id: "item_copper_bottle_filled_water",
    nameKey: "registry.item.item_copper_bottle_filled_water.name",
    iconId: "item_copper_bottle_filled_water",
    tags: ["瓶子", "瓶装液体"],
    displayOrder: 10000,
  },
  {
    id: "item_copper_bottle_filled_liquid_plant_grass_1",
    nameKey: "registry.item.item_copper_bottle_filled_liquid_plant_grass_1.name",
    iconId: "item_copper_bottle_filled_liquid_plant_grass_1",
    tags: ["瓶子", "瓶装液体"],
    displayOrder: 10000,
  },
  {
    id: "item_copper_bottle_filled_liquid_plant_grass_2",
    nameKey: "registry.item.item_copper_bottle_filled_liquid_plant_grass_2.name",
    iconId: "item_copper_bottle_filled_liquid_plant_grass_2",
    tags: ["瓶子", "瓶装液体"],
    displayOrder: 10000,
  },
  {
    id: "item_copper_bottle_filled_liquid_xiranite",
    nameKey: "registry.item.item_copper_bottle_filled_liquid_xiranite.name",
    iconId: "item_copper_bottle_filled_liquid_xiranite",
    tags: ["瓶子", "瓶装液体"],
    displayOrder: 10000,
  },
  {
    id: "item_copper_bottle_filled_liquid_sewage",
    nameKey: "registry.item.item_copper_bottle_filled_liquid_sewage.name",
    iconId: "item_copper_bottle_filled_liquid_sewage",
    tags: ["瓶子", "瓶装液体"],
    displayOrder: 10000,
  },
  {
    id: "item_copper_bottle_filled_liquid_xiranite_poly",
    nameKey: "registry.item.item_copper_bottle_filled_liquid_xiranite_poly.name",
    iconId: "item_copper_bottle_filled_liquid_xiranite_poly",
    tags: ["瓶子", "瓶装液体"],
    displayOrder: 10000,
  },
  {
    id: "item_copper_bottle_filled_liquid_xiranite_lowpoly",
    nameKey: "registry.item.item_copper_bottle_filled_liquid_xiranite_lowpoly.name",
    iconId: "item_copper_bottle_filled_liquid_xiranite_lowpoly",
    tags: ["瓶子", "瓶装液体"],
    displayOrder: 10000,
  },
  {
    id: "item_copper_enr_bottle",
    nameKey: "registry.item.item_copper_enr_bottle.name",
    iconId: "item_copper_enr_bottle",
    tags: ["瓶子", "new"],
    displayOrder: 10000,
  },
  {
    id: "item_copper_enr_bottle_filled_water",
    nameKey: "registry.item.item_copper_enr_bottle_filled_water.name",
    iconId: "item_copper_enr_bottle_filled_water",
    tags: ["瓶子", "瓶装液体", "new"],
    displayOrder: 10000,
  },
  {
    id: "item_copper_enr_bottle_filled_liquid_plant_grass_1",
    nameKey: "registry.item.item_copper_enr_bottle_filled_liquid_plant_grass_1.name",
    iconId: "item_copper_enr_bottle_filled_liquid_plant_grass_1",
    tags: ["瓶子", "瓶装液体", "new"],
    displayOrder: 10000,
  },
  {
    id: "item_copper_enr_bottle_filled_liquid_plant_grass_2",
    nameKey: "registry.item.item_copper_enr_bottle_filled_liquid_plant_grass_2.name",
    iconId: "item_copper_enr_bottle_filled_liquid_plant_grass_2",
    tags: ["瓶子", "瓶装液体", "new"],
    displayOrder: 10000,
  },
  {
    id: "item_copper_enr_bottle_filled_liquid_xiranite",
    nameKey: "registry.item.item_copper_enr_bottle_filled_liquid_xiranite.name",
    iconId: "item_copper_enr_bottle_filled_liquid_xiranite",
    tags: ["瓶子", "瓶装液体", "new"],
    displayOrder: 10000,
  },
  {
    id: "item_copper_enr_bottle_filled_liquid_sewage",
    nameKey: "registry.item.item_copper_enr_bottle_filled_liquid_sewage.name",
    iconId: "item_copper_enr_bottle_filled_liquid_sewage",
    tags: ["瓶子", "瓶装液体", "new"],
    displayOrder: 10000,
  },
  {
    id: "item_copper_enr_bottle_filled_liquid_xiranite_poly",
    nameKey: "registry.item.item_copper_enr_bottle_filled_liquid_xiranite_poly.name",
    iconId: "item_copper_enr_bottle_filled_liquid_xiranite_poly",
    tags: ["瓶子", "瓶装液体", "new"],
    displayOrder: 10000,
  },
  {
    id: "item_copper_enr_bottle_filled_liquid_xiranite_lowpoly",
    nameKey: "registry.item.item_copper_enr_bottle_filled_liquid_xiranite_lowpoly.name",
    iconId: "item_copper_enr_bottle_filled_liquid_xiranite_lowpoly",
    tags: ["瓶子", "瓶装液体", "new"],
    displayOrder: 10000,
  },
  {
    id: "item_copper_enr",
    nameKey: "registry.item.item_copper_enr.name",
    iconId: "item_copper_enr",
    tags: ["new"],
    displayOrder: 10000,
  },
  {
    id: "item_copper_powder",
    nameKey: "registry.item.item_copper_powder.name",
    iconId: "item_copper_powder",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_copper_nugget",
    nameKey: "registry.item.item_copper_nugget.name",
    iconId: "item_copper_nugget",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_liquid_acid",
    nameKey: "registry.item.item_liquid_acid.name",
    iconId: "item_liquid_acid",
    tags: ["liquid", "liquid_color:#d97a1f", "new", "自然资源", "无限供应"],
    displayOrder: 10000,
  },
  {
    id: "item_liquid_copper",
    nameKey: "registry.item.item_liquid_copper.name",
    iconId: "item_liquid_copper",
    tags: ["liquid", "liquid_color:#8b2a2a", "new"],
    displayOrder: 10000,
  },
  {
    id: "item_liquid_copper_enr",
    nameKey: "registry.item.item_liquid_copper_enr.name",
    iconId: "item_liquid_copper_enr",
    tags: ["liquid", "liquid_color:#6b0f1a", "new"],
    displayOrder: 10000,
  },
  {
    id: "item_liquid_sewage",
    nameKey: "registry.item.item_liquid_sewage.name",
    iconId: "item_liquid_sewage",
    tags: ["liquid", "liquid_color:#808080"],
    displayOrder: 10000,
  },
  {
    id: "item_liquid_xiranite_poly",
    nameKey: "registry.item.item_liquid_xiranite_poly.name",
    iconId: "item_liquid_xiranite_poly",
    tags: ["liquid", "liquid_color:#111111"],
    displayOrder: 10000,
  },
  {
    id: "item_liquid_xiranite_lowpoly",
    nameKey: "registry.item.item_liquid_xiranite_lowpoly.name",
    iconId: "item_liquid_xiranite_lowpoly",
    tags: ["liquid", "liquid_color:#4a2f1f"],
    displayOrder: 10000,
  },
  {
    id: "item_liquid_xiranite_enr",
    nameKey: "registry.item.item_liquid_xiranite_enr.name",
    iconId: "item_liquid_xiranite_enr",
    tags: ["liquid", "liquid_color:#0e6a47", "new"],
    displayOrder: 10000,
  },
  {
    id: "item_xiranite_poly",
    nameKey: "registry.item.item_xiranite_poly.name",
    iconId: "item_xiranite_poly",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_activity_xiranite_cmpt",
    nameKey: "registry.item.item_activity_xiranite_cmpt.name",
    iconId: "item_activity_xiranite_cmpt",
    tags: ["new", ACTIVITY_LIMITED_FORMULA_1_TAG],
    displayOrder: 10000,
  },
  {
    id: "item_activity_xiranite_enr_cmpt",
    nameKey: "registry.item.item_activity_xiranite_enr_cmpt.name",
    iconId: "item_activity_xiranite_enr_cmpt",
    tags: ["new", ACTIVITY_LIMITED_FORMULA_1_TAG],
    displayOrder: 10000,
  },
  {
    id: "item_activity_xiranite_bottle",
    nameKey: "registry.item.item_activity_xiranite_bottle.name",
    iconId: "item_activity_xiranite_bottle",
    tags: ["new", ACTIVITY_LIMITED_FORMULA_1_TAG],
    displayOrder: 10000,
  },
  {
    id: "item_activity_xiranite_enr_bottle",
    nameKey: "registry.item.item_activity_xiranite_enr_bottle.name",
    iconId: "item_activity_xiranite_enr_bottle",
    tags: ["new", ACTIVITY_LIMITED_FORMULA_1_TAG],
    displayOrder: 10000,
  },
  {
    id: "item_iron_bottle_filled_liquid_acid",
    nameKey: "registry.item.item_iron_bottle_filled_liquid_acid.name",
    iconId: "item_iron_bottle_filled_liquid_acid",
    tags: ["瓶子", "瓶装液体", "new"],
    displayOrder: 10000,
  },
  {
    id: "item_iron_bottle_filled_liquid_copper",
    nameKey: "registry.item.item_iron_bottle_filled_liquid_copper.name",
    iconId: "item_iron_bottle_filled_liquid_copper",
    tags: ["瓶子", "瓶装液体", "new"],
    displayOrder: 10000,
  },
  {
    id: "item_iron_bottle_filled_liquid_copper_enr",
    nameKey: "registry.item.item_iron_bottle_filled_liquid_copper_enr.name",
    iconId: "item_iron_bottle_filled_liquid_copper_enr",
    tags: ["瓶子", "瓶装液体", "new"],
    displayOrder: 10000,
  },
  {
    id: "item_iron_bottle_filled_liquid_xiranite_enr",
    nameKey: "registry.item.item_iron_bottle_filled_liquid_xiranite_enr.name",
    iconId: "item_iron_bottle_filled_liquid_xiranite_enr",
    tags: ["瓶子", "瓶装液体", "new"],
    displayOrder: 10000,
  },
  {
    id: "item_glass_bottle_filled_liquid_acid",
    nameKey: "registry.item.item_glass_bottle_filled_liquid_acid.name",
    iconId: "item_glass_bottle_filled_liquid_acid",
    tags: ["瓶子", "瓶装液体", "new"],
    displayOrder: 10000,
  },
  {
    id: "item_glass_bottle_filled_liquid_copper",
    nameKey: "registry.item.item_glass_bottle_filled_liquid_copper.name",
    iconId: "item_glass_bottle_filled_liquid_copper",
    tags: ["瓶子", "瓶装液体", "new"],
    displayOrder: 10000,
  },
  {
    id: "item_glass_bottle_filled_liquid_copper_enr",
    nameKey: "registry.item.item_glass_bottle_filled_liquid_copper_enr.name",
    iconId: "item_glass_bottle_filled_liquid_copper_enr",
    tags: ["瓶子", "瓶装液体", "new"],
    displayOrder: 10000,
  },
  {
    id: "item_glass_bottle_filled_liquid_xiranite_enr",
    nameKey: "registry.item.item_glass_bottle_filled_liquid_xiranite_enr.name",
    iconId: "item_glass_bottle_filled_liquid_xiranite_enr",
    tags: ["瓶子", "瓶装液体", "new"],
    displayOrder: 10000,
  },
  {
    id: "item_glass_enr_bottle_filled_liquid_acid",
    nameKey: "registry.item.item_glass_enr_bottle_filled_liquid_acid.name",
    iconId: "item_glass_enr_bottle_filled_liquid_acid",
    tags: ["瓶子", "瓶装液体", "new"],
    displayOrder: 10000,
  },
  {
    id: "item_glass_enr_bottle_filled_liquid_copper",
    nameKey: "registry.item.item_glass_enr_bottle_filled_liquid_copper.name",
    iconId: "item_glass_enr_bottle_filled_liquid_copper",
    tags: ["瓶子", "瓶装液体", "new"],
    displayOrder: 10000,
  },
  {
    id: "item_glass_enr_bottle_filled_liquid_copper_enr",
    nameKey: "registry.item.item_glass_enr_bottle_filled_liquid_copper_enr.name",
    iconId: "item_glass_enr_bottle_filled_liquid_copper_enr",
    tags: ["瓶子", "瓶装液体", "new"],
    displayOrder: 10000,
  },
  {
    id: "item_glass_enr_bottle_filled_liquid_xiranite_enr",
    nameKey: "registry.item.item_glass_enr_bottle_filled_liquid_xiranite_enr.name",
    iconId: "item_glass_enr_bottle_filled_liquid_xiranite_enr",
    tags: ["瓶子", "瓶装液体", "new"],
    displayOrder: 10000,
  },
  {
    id: "item_iron_enr_bottle_filled_liquid_acid",
    nameKey: "registry.item.item_iron_enr_bottle_filled_liquid_acid.name",
    iconId: "item_iron_enr_bottle_filled_liquid_acid",
    tags: ["瓶子", "瓶装液体", "new"],
    displayOrder: 10000,
  },
  {
    id: "item_iron_enr_bottle_filled_liquid_copper",
    nameKey: "registry.item.item_iron_enr_bottle_filled_liquid_copper.name",
    iconId: "item_iron_enr_bottle_filled_liquid_copper",
    tags: ["瓶子", "瓶装液体", "new"],
    displayOrder: 10000,
  },
  {
    id: "item_iron_enr_bottle_filled_liquid_copper_enr",
    nameKey: "registry.item.item_iron_enr_bottle_filled_liquid_copper_enr.name",
    iconId: "item_iron_enr_bottle_filled_liquid_copper_enr",
    tags: ["瓶子", "瓶装液体", "new"],
    displayOrder: 10000,
  },
  {
    id: "item_iron_enr_bottle_filled_liquid_xiranite_enr",
    nameKey: "registry.item.item_iron_enr_bottle_filled_liquid_xiranite_enr.name",
    iconId: "item_iron_enr_bottle_filled_liquid_xiranite_enr",
    tags: ["瓶子", "瓶装液体", "new"],
    displayOrder: 10000,
  },
  {
    id: "item_copper_bottle_filled_liquid_acid",
    nameKey: "registry.item.item_copper_bottle_filled_liquid_acid.name",
    iconId: "item_copper_bottle_filled_liquid_acid",
    tags: ["瓶子", "瓶装液体", "new"],
    displayOrder: 10000,
  },
  {
    id: "item_copper_bottle_filled_liquid_copper",
    nameKey: "registry.item.item_copper_bottle_filled_liquid_copper.name",
    iconId: "item_copper_bottle_filled_liquid_copper",
    tags: ["瓶子", "瓶装液体", "new"],
    displayOrder: 10000,
  },
  {
    id: "item_copper_bottle_filled_liquid_copper_enr",
    nameKey: "registry.item.item_copper_bottle_filled_liquid_copper_enr.name",
    iconId: "item_copper_bottle_filled_liquid_copper_enr",
    tags: ["瓶子", "瓶装液体", "new"],
    displayOrder: 10000,
  },
  {
    id: "item_copper_bottle_filled_liquid_xiranite_enr",
    nameKey: "registry.item.item_copper_bottle_filled_liquid_xiranite_enr.name",
    iconId: "item_copper_bottle_filled_liquid_xiranite_enr",
    tags: ["瓶子", "瓶装液体", "new"],
    displayOrder: 10000,
  },
  {
    id: "item_copper_enr_bottle_filled_liquid_acid",
    nameKey: "registry.item.item_copper_enr_bottle_filled_liquid_acid.name",
    iconId: "item_copper_enr_bottle_filled_liquid_acid",
    tags: ["瓶子", "瓶装液体", "new"],
    displayOrder: 10000,
  },
  {
    id: "item_copper_enr_bottle_filled_liquid_copper",
    nameKey: "registry.item.item_copper_enr_bottle_filled_liquid_copper.name",
    iconId: "item_copper_enr_bottle_filled_liquid_copper",
    tags: ["瓶子", "瓶装液体", "new"],
    displayOrder: 10000,
  },
  {
    id: "item_copper_enr_bottle_filled_liquid_copper_enr",
    nameKey: "registry.item.item_copper_enr_bottle_filled_liquid_copper_enr.name",
    iconId: "item_copper_enr_bottle_filled_liquid_copper_enr",
    tags: ["瓶子", "瓶装液体", "new"],
    displayOrder: 10000,
  },
  {
    id: "item_copper_enr_bottle_filled_liquid_xiranite_enr",
    nameKey: "registry.item.item_copper_enr_bottle_filled_liquid_xiranite_enr.name",
    iconId: "item_copper_enr_bottle_filled_liquid_xiranite_enr",
    tags: ["瓶子", "瓶装液体", "new"],
    displayOrder: 10000,
  },
  {
    id: "item_activity_xiranite_enr_bottle_filled_liquid_plant_grass_2",
    nameKey: "registry.item.item_activity_xiranite_enr_bottle_filled_liquid_plant_grass_2.name",
    iconId: "item_activity_xiranite_enr_bottle_filled_liquid_plant_grass_2",
    tags: ["new", ACTIVITY_LIMITED_FORMULA_1_TAG],
    displayOrder: 10000,
  },
  {
    id: "item_activity_xiranite_enr_tool",
    nameKey: "registry.item.item_activity_xiranite_enr_tool.name",
    iconId: "item_activity_xiranite_enr_tool",
    tags: ["new", ACTIVITY_LIMITED_FORMULA_1_TAG],
    displayOrder: 10000,
  },
  {
    id: "item_activity_xiranite_hulu",
    nameKey: "registry.item.item_activity_xiranite_hulu.name",
    iconId: "item_activity_xiranite_hulu",
    tags: ["new", ACTIVITY_LIMITED_FORMULA_1_TAG],
    displayOrder: 10000,
  },
  {
    id: "item_activity_xiranite_enr_hulu",
    nameKey: "registry.item.item_activity_xiranite_enr_hulu.name",
    iconId: "item_activity_xiranite_enr_hulu",
    tags: ["new", ACTIVITY_LIMITED_FORMULA_1_TAG],
    displayOrder: 10000,
  },
  {
    id: "item_copper_cmpt",
    nameKey: "registry.item.item_copper_cmpt.name",
    iconId: "item_copper_cmpt",
    tags: ["调度券地区:武陵", "调度券价值:1"],
    displayOrder: 10000,
  },
  {
    id: "item_copper_enr_cmpt",
    nameKey: "registry.item.item_copper_enr_cmpt.name",
    iconId: "item_copper_enr_cmpt",
    tags: ["new", "调度券地区:武陵", "调度券价值:48"],
    displayOrder: 10000,
  },
  {
    id: "item_equip_script_1",
    nameKey: "registry.item.item_equip_script_1.name",
    iconId: "item_equip_script_1",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_equip_script_2",
    nameKey: "registry.item.item_equip_script_2.name",
    iconId: "item_equip_script_2",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_equip_script_3",
    nameKey: "registry.item.item_equip_script_3.name",
    iconId: "item_equip_script_3",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_equip_script_4",
    nameKey: "registry.item.item_equip_script_4.name",
    iconId: "item_equip_script_4",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_equip_script_4_1",
    nameKey: "registry.item.item_equip_script_4_1.name",
    iconId: "item_equip_script_4_1",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_equip_script_4_2",
    nameKey: "registry.item.item_equip_script_4_2.name",
    iconId: "item_equip_script_4_2",
    tags: ["new"],
    displayOrder: 10000,
  },
  {
    id: "item_glass_bottle",
    nameKey: "registry.item.item_glass_bottle.name",
    iconId: "item_glass_bottle",
    tags: ["瓶子"],
    displayOrder: 10000,
  },
  {
    id: "item_glass_bottle_filled_water",
    nameKey: "registry.item.item_glass_bottle_filled_water.name",
    iconId: "item_glass_bottle_filled_water",
    tags: ["瓶子", "瓶装液体"],
    displayOrder: 10000,
  },
  {
    id: "item_glass_bottle_filled_liquid_plant_grass_1",
    nameKey: "registry.item.item_glass_bottle_filled_liquid_plant_grass_1.name",
    iconId: "item_glass_bottle_filled_liquid_plant_grass_1",
    tags: ["瓶子", "瓶装液体"],
    displayOrder: 10000,
  },
  {
    id: "item_glass_bottle_filled_liquid_plant_grass_2",
    nameKey: "registry.item.item_glass_bottle_filled_liquid_plant_grass_2.name",
    iconId: "item_glass_bottle_filled_liquid_plant_grass_2",
    tags: ["瓶子", "瓶装液体"],
    displayOrder: 10000,
  },
  {
    id: "item_glass_bottle_filled_liquid_xiranite",
    nameKey: "registry.item.item_glass_bottle_filled_liquid_xiranite.name",
    iconId: "item_glass_bottle_filled_liquid_xiranite",
    tags: ["瓶子", "瓶装液体"],
    displayOrder: 10000,
  },
  {
    id: "item_glass_bottle_filled_liquid_sewage",
    nameKey: "registry.item.item_glass_bottle_filled_liquid_sewage.name",
    iconId: "item_glass_bottle_filled_liquid_sewage",
    tags: ["瓶子", "瓶装液体"],
    displayOrder: 10000,
  },
  {
    id: "item_glass_bottle_filled_liquid_xiranite_poly",
    nameKey: "registry.item.item_glass_bottle_filled_liquid_xiranite_poly.name",
    iconId: "item_glass_bottle_filled_liquid_xiranite_poly",
    tags: ["瓶子", "瓶装液体"],
    displayOrder: 10000,
  },
  {
    id: "item_glass_bottle_filled_liquid_xiranite_lowpoly",
    nameKey: "registry.item.item_glass_bottle_filled_liquid_xiranite_lowpoly.name",
    iconId: "item_glass_bottle_filled_liquid_xiranite_lowpoly",
    tags: ["瓶子", "瓶装液体"],
    displayOrder: 10000,
  },
  {
    id: "item_glass_cmpt",
    nameKey: "registry.item.item_glass_cmpt.name",
    iconId: "item_glass_cmpt",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_glass_enr_bottle",
    nameKey: "registry.item.item_glass_enr_bottle.name",
    iconId: "item_glass_enr_bottle",
    tags: ["瓶子"],
    displayOrder: 10000,
  },
  {
    id: "item_glass_enr_bottle_filled_water",
    nameKey: "registry.item.item_glass_enr_bottle_filled_water.name",
    iconId: "item_glass_enr_bottle_filled_water",
    tags: ["瓶子", "瓶装液体"],
    displayOrder: 10000,
  },
  {
    id: "item_glass_enr_bottle_filled_liquid_plant_grass_1",
    nameKey: "registry.item.item_glass_enr_bottle_filled_liquid_plant_grass_1.name",
    iconId: "item_glass_enr_bottle_filled_liquid_plant_grass_1",
    tags: ["瓶子", "瓶装液体"],
    displayOrder: 10000,
  },
  {
    id: "item_glass_enr_bottle_filled_liquid_plant_grass_2",
    nameKey: "registry.item.item_glass_enr_bottle_filled_liquid_plant_grass_2.name",
    iconId: "item_glass_enr_bottle_filled_liquid_plant_grass_2",
    tags: ["瓶子", "瓶装液体"],
    displayOrder: 10000,
  },
  {
    id: "item_glass_enr_bottle_filled_liquid_xiranite",
    nameKey: "registry.item.item_glass_enr_bottle_filled_liquid_xiranite.name",
    iconId: "item_glass_enr_bottle_filled_liquid_xiranite",
    tags: ["瓶子", "瓶装液体"],
    displayOrder: 10000,
  },
  {
    id: "item_glass_enr_bottle_filled_liquid_sewage",
    nameKey: "registry.item.item_glass_enr_bottle_filled_liquid_sewage.name",
    iconId: "item_glass_enr_bottle_filled_liquid_sewage",
    tags: ["瓶子", "瓶装液体"],
    displayOrder: 10000,
  },
  {
    id: "item_glass_enr_bottle_filled_liquid_xiranite_poly",
    nameKey: "registry.item.item_glass_enr_bottle_filled_liquid_xiranite_poly.name",
    iconId: "item_glass_enr_bottle_filled_liquid_xiranite_poly",
    tags: ["瓶子", "瓶装液体"],
    displayOrder: 10000,
  },
  {
    id: "item_glass_enr_bottle_filled_liquid_xiranite_lowpoly",
    nameKey: "registry.item.item_glass_enr_bottle_filled_liquid_xiranite_lowpoly.name",
    iconId: "item_glass_enr_bottle_filled_liquid_xiranite_lowpoly",
    tags: ["瓶子", "瓶装液体"],
    displayOrder: 10000,
  },
  {
    id: "item_glass_enr_cmpt",
    nameKey: "registry.item.item_glass_enr_cmpt.name",
    iconId: "item_glass_enr_cmpt",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_iron_bottle",
    nameKey: "registry.item.item_iron_bottle.name",
    iconId: "item_iron_bottle",
    tags: ["瓶子"],
    displayOrder: 10000,
  },
  {
    id: "item_iron_bottle_filled_water",
    nameKey: "registry.item.item_iron_bottle_filled_water.name",
    iconId: "item_iron_bottle_filled_water",
    tags: ["瓶子", "瓶装液体"],
    displayOrder: 10000,
  },
  {
    id: "item_iron_bottle_filled_liquid_plant_grass_1",
    nameKey: "registry.item.item_iron_bottle_filled_liquid_plant_grass_1.name",
    iconId: "item_iron_bottle_filled_liquid_plant_grass_1",
    tags: ["瓶子", "瓶装液体"],
    displayOrder: 10000,
  },
  {
    id: "item_iron_bottle_filled_liquid_plant_grass_2",
    nameKey: "registry.item.item_iron_bottle_filled_liquid_plant_grass_2.name",
    iconId: "item_iron_bottle_filled_liquid_plant_grass_2",
    tags: ["瓶子", "瓶装液体"],
    displayOrder: 10000,
  },
  {
    id: "item_iron_bottle_filled_liquid_xiranite",
    nameKey: "registry.item.item_iron_bottle_filled_liquid_xiranite.name",
    iconId: "item_iron_bottle_filled_liquid_xiranite",
    tags: ["瓶子", "瓶装液体"],
    displayOrder: 10000,
  },
  {
    id: "item_iron_bottle_filled_liquid_sewage",
    nameKey: "registry.item.item_iron_bottle_filled_liquid_sewage.name",
    iconId: "item_iron_bottle_filled_liquid_sewage",
    tags: ["瓶子", "瓶装液体"],
    displayOrder: 10000,
  },
  {
    id: "item_iron_bottle_filled_liquid_xiranite_poly",
    nameKey: "registry.item.item_iron_bottle_filled_liquid_xiranite_poly.name",
    iconId: "item_iron_bottle_filled_liquid_xiranite_poly",
    tags: ["瓶子", "瓶装液体"],
    displayOrder: 10000,
  },
  {
    id: "item_iron_bottle_filled_liquid_xiranite_lowpoly",
    nameKey: "registry.item.item_iron_bottle_filled_liquid_xiranite_lowpoly.name",
    iconId: "item_iron_bottle_filled_liquid_xiranite_lowpoly",
    tags: ["瓶子", "瓶装液体"],
    displayOrder: 10000,
  },
  {
    id: "item_iron_cmpt",
    nameKey: "registry.item.item_iron_cmpt.name",
    iconId: "item_iron_cmpt",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_iron_enr",
    nameKey: "registry.item.item_iron_enr.name",
    iconId: "item_iron_enr",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_iron_enr_bottle",
    nameKey: "registry.item.item_iron_enr_bottle.name",
    iconId: "item_iron_enr_bottle",
    tags: ["瓶子"],
    displayOrder: 10000,
  },
  {
    id: "item_iron_enr_bottle_filled_water",
    nameKey: "registry.item.item_iron_enr_bottle_filled_water.name",
    iconId: "item_iron_enr_bottle_filled_water",
    tags: ["瓶子", "瓶装液体"],
    displayOrder: 10000,
  },
  {
    id: "item_iron_enr_bottle_filled_liquid_plant_grass_1",
    nameKey: "registry.item.item_iron_enr_bottle_filled_liquid_plant_grass_1.name",
    iconId: "item_iron_enr_bottle_filled_liquid_plant_grass_1",
    tags: ["瓶子", "瓶装液体"],
    displayOrder: 10000,
  },
  {
    id: "item_iron_enr_bottle_filled_liquid_plant_grass_2",
    nameKey: "registry.item.item_iron_enr_bottle_filled_liquid_plant_grass_2.name",
    iconId: "item_iron_enr_bottle_filled_liquid_plant_grass_2",
    tags: ["瓶子", "瓶装液体"],
    displayOrder: 10000,
  },
  {
    id: "item_iron_enr_bottle_filled_liquid_xiranite",
    nameKey: "registry.item.item_iron_enr_bottle_filled_liquid_xiranite.name",
    iconId: "item_iron_enr_bottle_filled_liquid_xiranite",
    tags: ["瓶子", "瓶装液体"],
    displayOrder: 10000,
  },
  {
    id: "item_iron_enr_bottle_filled_liquid_sewage",
    nameKey: "registry.item.item_iron_enr_bottle_filled_liquid_sewage.name",
    iconId: "item_iron_enr_bottle_filled_liquid_sewage",
    tags: ["瓶子", "瓶装液体"],
    displayOrder: 10000,
  },
  {
    id: "item_iron_enr_bottle_filled_liquid_xiranite_poly",
    nameKey: "registry.item.item_iron_enr_bottle_filled_liquid_xiranite_poly.name",
    iconId: "item_iron_enr_bottle_filled_liquid_xiranite_poly",
    tags: ["瓶子", "瓶装液体"],
    displayOrder: 10000,
  },
  {
    id: "item_iron_enr_bottle_filled_liquid_xiranite_lowpoly",
    nameKey: "registry.item.item_iron_enr_bottle_filled_liquid_xiranite_lowpoly.name",
    iconId: "item_iron_enr_bottle_filled_liquid_xiranite_lowpoly",
    tags: ["瓶子", "瓶装液体"],
    displayOrder: 10000,
  },
  {
    id: "item_iron_enr_cmpt",
    nameKey: "registry.item.item_iron_enr_cmpt.name",
    iconId: "item_iron_enr_cmpt",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_iron_enr_powder",
    nameKey: "registry.item.item_iron_enr_powder.name",
    iconId: "item_iron_enr_powder",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_iron_nugget",
    nameKey: "registry.item.item_iron_nugget.name",
    iconId: "item_iron_nugget",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_iron_ore",
    nameKey: "registry.item.item_iron_ore.name",
    iconId: "item_iron_ore",
    tags: ["矿石", "自然资源"],
    displayOrder: 10000,
  },
  {
    id: "item_iron_powder",
    nameKey: "registry.item.item_iron_powder.name",
    iconId: "item_iron_powder",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_liquid_plant_grass_1",
    nameKey: "registry.item.item_liquid_plant_grass_1.name",
    iconId: "item_liquid_plant_grass_1",
    tags: ["liquid", "liquid_color:#35c8b6"],
    displayOrder: 10000,
  },
  {
    id: "item_liquid_plant_grass_2",
    nameKey: "registry.item.item_liquid_plant_grass_2.name",
    iconId: "item_liquid_plant_grass_2",
    tags: ["liquid", "liquid_color:#9be870"],
    displayOrder: 10000,
  },
  {
    id: "item_liquid_water",
    nameKey: "registry.item.item_liquid_water.name",
    iconId: "item_liquid_water",
    tags: ["liquid", "liquid_color:#82d6ff", "自然资源", "无限供应"],
    displayOrder: 10000,
  },
  {
    id: "item_liquid_xiranite",
    nameKey: "registry.item.item_liquid_xiranite.name",
    iconId: "item_liquid_xiranite",
    tags: ["liquid", "liquid_color:#1f7a3a"],
    displayOrder: 10000,
  },
  {
    id: "item_gas_inert",
    nameKey: "registry.item.item_gas_inert.name",
    iconId: "item_liquid_water",
    tags: ["gas", "gas_color:#3366cc"],
    displayOrder: 10000,
  },
  {
    id: "item_gas_xiranite",
    nameKey: "registry.item.item_gas_xiranite.name",
    iconId: "item_liquid_plant_grass_2",
    tags: ["gas", "gas_color:#62bf4b"],
    displayOrder: 10000,
  },
  {
    id: "item_muck_feces_1",
    nameKey: "registry.item.item_muck_feces_1.name",
    iconId: "item_muck_feces_1",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_muck_xiranite_1",
    nameKey: "registry.item.item_muck_xiranite_1.name",
    iconId: "item_muck_xiranite_1",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_originium_enr_powder",
    nameKey: "registry.item.item_originium_enr_powder.name",
    iconId: "item_originium_enr_powder",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_originium_ore",
    nameKey: "registry.item.item_originium_ore.name",
    iconId: "item_originium_ore",
    tags: ["矿石", "自然资源"],
    displayOrder: 10000,
  },
  {
    id: "item_originium_powder",
    nameKey: "registry.item.item_originium_powder.name",
    iconId: "item_originium_powder",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_plant_bbflower_1",
    nameKey: "registry.item.item_plant_bbflower_1.name",
    iconId: "item_plant_bbflower_1",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_plant_bbflower_powder_1",
    nameKey: "registry.item.item_plant_bbflower_powder_1.name",
    iconId: "item_plant_bbflower_powder_1",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_plant_bbflower_seed_1",
    nameKey: "registry.item.item_plant_bbflower_seed_1.name",
    iconId: "item_plant_bbflower_seed_1",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_plant_grass_1",
    nameKey: "registry.item.item_plant_grass_1.name",
    iconId: "item_plant_grass_1",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_plant_grass_2",
    nameKey: "registry.item.item_plant_grass_2.name",
    iconId: "item_plant_grass_2",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_plant_grass_powder_1",
    nameKey: "registry.item.item_plant_grass_powder_1.name",
    iconId: "item_plant_grass_powder_1",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_plant_grass_powder_2",
    nameKey: "registry.item.item_plant_grass_powder_2.name",
    iconId: "item_plant_grass_powder_2",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_plant_grass_seed_1",
    nameKey: "registry.item.item_plant_grass_seed_1.name",
    iconId: "item_plant_grass_seed_1",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_plant_grass_seed_2",
    nameKey: "registry.item.item_plant_grass_seed_2.name",
    iconId: "item_plant_grass_seed_2",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_plant_moss_1",
    nameKey: "registry.item.item_plant_moss_1.name",
    iconId: "item_plant_moss_1",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_plant_moss_2",
    nameKey: "registry.item.item_plant_moss_2.name",
    iconId: "item_plant_moss_2",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_plant_moss_3",
    nameKey: "registry.item.item_plant_moss_3.name",
    iconId: "item_plant_moss_3",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_plant_moss_enr_powder_1",
    nameKey: "registry.item.item_plant_moss_enr_powder_1.name",
    iconId: "item_plant_moss_enr_powder_1",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_plant_moss_enr_powder_2",
    nameKey: "registry.item.item_plant_moss_enr_powder_2.name",
    iconId: "item_plant_moss_enr_powder_2",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_plant_moss_powder_1",
    nameKey: "registry.item.item_plant_moss_powder_1.name",
    iconId: "item_plant_moss_powder_1",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_plant_moss_powder_2",
    nameKey: "registry.item.item_plant_moss_powder_2.name",
    iconId: "item_plant_moss_powder_2",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_plant_moss_powder_3",
    nameKey: "registry.item.item_plant_moss_powder_3.name",
    iconId: "item_plant_moss_powder_3",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_plant_moss_seed_1",
    nameKey: "registry.item.item_plant_moss_seed_1.name",
    iconId: "item_plant_moss_seed_1",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_plant_moss_seed_2",
    nameKey: "registry.item.item_plant_moss_seed_2.name",
    iconId: "item_plant_moss_seed_2",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_plant_moss_seed_3",
    nameKey: "registry.item.item_plant_moss_seed_3.name",
    iconId: "item_plant_moss_seed_3",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_proc_battery_1",
    nameKey: "registry.item.item_proc_battery_1.name",
    iconId: "item_proc_battery_1",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_proc_battery_2",
    nameKey: "registry.item.item_proc_battery_2.name",
    iconId: "item_proc_battery_2",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_proc_battery_3",
    nameKey: "registry.item.item_proc_battery_3.name",
    iconId: "item_proc_battery_3",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_proc_battery_4",
    nameKey: "registry.item.item_proc_battery_4.name",
    iconId: "item_proc_battery_4",
    tags: ["调度券地区:武陵", "调度券价值:25"],
    displayOrder: 10000,
  },
  {
    id: "item_proc_battery_5",
    nameKey: "registry.item.item_proc_battery_5.name",
    iconId: "item_proc_battery_5",
    tags: ["调度券地区:武陵", "调度券价值:54"],
    displayOrder: 10000,
  },
  {
    id: "item_proc_bomb_1",
    nameKey: "registry.item.item_proc_bomb_1.name",
    iconId: "item_proc_bomb_1",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_quartz_enr",
    nameKey: "registry.item.item_quartz_enr.name",
    iconId: "item_quartz_enr",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_quartz_enr_powder",
    nameKey: "registry.item.item_quartz_enr_powder.name",
    iconId: "item_quartz_enr_powder",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_quartz_glass",
    nameKey: "registry.item.item_quartz_glass.name",
    iconId: "item_quartz_glass",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_quartz_powder",
    nameKey: "registry.item.item_quartz_powder.name",
    iconId: "item_quartz_powder",
    tags: [],
    displayOrder: 10000,
  },
  {
    id: "item_quartz_sand",
    nameKey: "registry.item.item_quartz_sand.name",
    iconId: "item_quartz_sand",
    tags: ["矿石", "自然资源"],
    displayOrder: 10000,
  },
  {
    id: "item_xiranite_enr_powder",
    nameKey: "registry.item.item_xiranite_enr_powder.name",
    iconId: "item_xiranite_enr_powder",
    tags: ["new", "调度券地区:武陵", "调度券价值:27"],
    displayOrder: 10000,
  },
  {
    id: "item_xiranite_powder",
    nameKey: "registry.item.item_xiranite_powder.name",
    iconId: "item_xiranite_powder",
    tags: ["调度券地区:武陵", "调度券价值:1"],
    displayOrder: 10000,
  },
];
