export const ENTITY_DEFINITIONS: EntityDefinition[] = [
  {
    id: "item_port_storager_1",
    nameKey: "registry.entity.item_port_storager_1.name",
    name: "Protocol Storage Box",
    category: "storage",
    footprint: { width: 3, height: 3 },
    capabilityIds: ["footprint", "inventory-buffer", "warehouse-attachment"],
    configFields: [
      {
        key: "submitToWarehouse",
        labelKey: "registry.config.submitToWarehouse.label",
        label: "Submit To Warehouse",
        mutability: "runtime-mutable",
      },
    ],
  },
  {
    id: "item_port_log_hongs_bus",
    nameKey: "registry.entity.item_port_log_hongs_bus.name",
    name: "Warehouse Bus Segment",
    category: "bus",
    footprint: { width: 4, height: 8 },
    capabilityIds: ["footprint", "warehouse-bus"],
    configFields: [],
  },
  {
    id: "item_port_log_hongs_bus_source",
    nameKey: "registry.entity.item_port_log_hongs_bus_source.name",
    name: "Warehouse Bus Source",
    category: "bus",
    footprint: { width: 4, height: 4 },
    capabilityIds: ["footprint", "warehouse-bus", "warehouse-source"],
    configFields: [],
  },
  {
    id: "item_port_unloader_1",
    nameKey: "registry.entity.item_port_unloader_1.name",
    name: "Pickup Port",
    category: "logistics",
    footprint: { width: 3, height: 1 },
    capabilityIds: ["footprint", "port-schema", "warehouse-pickup"],
    configFields: [
      {
        key: "pickupIgnoreInventory",
        labelKey: "registry.config.pickupIgnoreInventory.label",
        label: "Ignore Source Inventory",
        mutability: "runtime-mutable",
      },
    ],
  },
  {
    id: "item_port_mix_pool_1",
    nameKey: "registry.entity.item_port_mix_pool_1.name",
    name: "Reactor Pool",
    category: "processor",
    footprint: { width: 5, height: 5 },
    capabilityIds: [
      "footprint",
      "port-schema",
      "recipe-processor",
      "parallel-recipe",
      "shared-slot-pool",
      "power-behavior",
    ],
    configFields: [
      {
        key: "selectedRecipeIds",
        labelKey: "registry.config.selectedRecipeIds.label",
        label: "Selected Recipes",
        mutability: "runtime-mutable",
      },
      {
        key: "outputRoutes",
        labelKey: "registry.config.outputRoutes.label",
        label: "Output Routes",
        mutability: "runtime-mutable",
      },
    ],
  },
  {
    id: "item_port_grinder_1",
    nameKey: "registry.entity.item_port_grinder_1.name",
    name: "Grinder",
    category: "processor",
    footprint: { width: 3, height: 3 },
    capabilityIds: [
      "footprint",
      "port-schema",
      "recipe-processor",
      "power-behavior",
    ],
    configFields: [],
  },
  {
    id: "item_port_liquid_filling_pd_mc_1",
    nameKey: "registry.entity.item_port_liquid_filling_pd_mc_1.name",
    name: "Liquid Filling Machine",
    category: "processor",
    footprint: { width: 6, height: 4 },
    capabilityIds: [
      "footprint",
      "port-schema",
      "recipe-processor",
      "power-behavior",
    ],
    configFields: [],
  },
  {
    id: "belt_straight_1x1",
    nameKey: "registry.entity.belt_straight_1x1.name",
    name: "Belt Straight",
    category: "track",
    footprint: { width: 1, height: 1 },
    capabilityIds: ["footprint", "conveyor-track"],
    configFields: [],
  },
  {
    id: "item_log_splitter",
    nameKey: "registry.entity.item_log_splitter.name",
    name: "Belt Splitter",
    category: "track",
    footprint: { width: 1, height: 1 },
    capabilityIds: ["footprint", "conveyor-track", "splitter"],
    configFields: [],
  },
  {
    id: "item_log_converger",
    nameKey: "registry.entity.item_log_converger.name",
    name: "Belt Converger",
    category: "track",
    footprint: { width: 1, height: 1 },
    capabilityIds: ["footprint", "conveyor-track", "converger"],
    configFields: [],
  },
  {
    id: "item_log_connector",
    nameKey: "registry.entity.item_log_connector.name",
    name: "Belt Bridge",
    category: "track",
    footprint: { width: 1, height: 1 },
    capabilityIds: ["footprint", "conveyor-track", "bridge-isolation"],
    configFields: [],
  },
  {
    id: "pipe_straight_1x1",
    nameKey: "registry.entity.pipe_straight_1x1.name",
    name: "Pipe Straight",
    category: "track",
    footprint: { width: 1, height: 1 },
    capabilityIds: ["footprint", "pipe-track"],
    configFields: [],
  },
  {
    id: "item_pipe_splitter",
    nameKey: "registry.entity.item_pipe_splitter.name",
    name: "Pipe Splitter",
    category: "track",
    footprint: { width: 1, height: 1 },
    capabilityIds: ["footprint", "pipe-track", "splitter"],
    configFields: [],
  },
  {
    id: "item_pipe_converger",
    nameKey: "registry.entity.item_pipe_converger.name",
    name: "Pipe Converger",
    category: "track",
    footprint: { width: 1, height: 1 },
    capabilityIds: ["footprint", "pipe-track", "converger"],
    configFields: [],
  },
  {
    id: "item_pipe_connector",
    nameKey: "registry.entity.item_pipe_connector.name",
    name: "Pipe Bridge",
    category: "track",
    footprint: { width: 1, height: 1 },
    capabilityIds: ["footprint", "pipe-track", "bridge-isolation"],
    configFields: [],
  },
  {
    id: "item_port_udpipe_loader_1",
    nameKey: "registry.entity.item_port_udpipe_loader_1.name",
    name: "Dark Pipe Inlet",
    category: "dark-pipe",
    footprint: { width: 3, height: 3 },
    capabilityIds: [
      "footprint",
      "port-schema",
      "device-link-source",
      "liquid-destroy-or-forward",
    ],
    configFields: [
      {
        key: "targetEntityId",
        labelKey: "registry.config.targetEntityId.label",
        label: "Linked Outlet",
        mutability: "recompile-required",
      },
    ],
  },
  {
    id: "item_port_udpipe_unloader_1",
    nameKey: "registry.entity.item_port_udpipe_unloader_1.name",
    name: "Dark Pipe Outlet",
    category: "dark-pipe",
    footprint: { width: 3, height: 3 },
    capabilityIds: [
      "footprint",
      "port-schema",
      "device-link-target",
      "external-liquid-source",
    ],
    configFields: [
      {
        key: "selectedLiquidItemId",
        labelKey: "registry.config.selectedLiquidItemId.label",
        label: "Selected Liquid",
        mutability: "runtime-mutable",
      },
    ],
  },
];
